function report = verify_solver(doPlot)
%VERIFY_SOLVER Verify initial guess, Picard iteration, and continuation.

if nargin < 1
    doPlot = true;
end
validateattributes(doPlot, {'logical', 'numeric'}, ...
    {'real', 'finite', 'scalar'}, mfilename, 'doPlot');
doPlot = logical(doPlot);

dependencies = {'make_boundary', 'generate_mesh', 'assemble_stiffness', ...
    'assemble_rhs', 'apply_dirichlet', 'make_profiles', 'gs_source'};
for k = 1:numel(dependencies)
    if exist(dependencies{k}, 'file') ~= 2
        error('GS:solver:MissingDependency', ...
            'Required function %s is not on the MATLAB path.', dependencies{k});
    end
end

params = struct( ...
    'A', 3.0, 'B', 0.9, 'C', 0.22, ...
    'G', 1.1, 'H', 0.06, 'nBoundary', 120);
geom = make_boundary(params);
meshData = generate_mesh(geom, struct('targetH', 0.14));
K = assemble_stiffness(meshData);
[psi0, initialInfo] = initial_guess(meshData, K, ...
    struct('boundaryValue', 0, 'axisValue', -1));
assert(max(abs(psi0(meshData.boundaryNodes))) == 0, ...
    'Initial guess does not satisfy the LCFS value exactly.');
assert(abs(min(psi0(meshData.interiorNodes))+1) < 1e-13, ...
    'Initial guess does not have the requested axis amplitude.');

% Linear constant-source solve: Picard must reproduce a direct FEM solve.
linearProfiles = make_profiles(struct( ...
    'pprime', struct('type', 'constant', 'value', 0), ...
    'FFprime', struct('type', 'constant', 'value', -1)));
linearOptions = struct( ...
    'tolerance', 1e-12, 'residualTolerance', 1e-12, ...
    'maxIterations', 10, 'omega', 1.0, ...
    'boundaryValue', 0, 'axisMode', 'min', ...
    'updateFluxAxis', true, 'verbose', false);
[psiLinear, linearResult] = solve_picard( ...
    meshData, linearProfiles, psi0, linearOptions);
rhsLinear = assemble_rhs(meshData, ...
    @(R,Z,psi) gs_source(R,Z,psi,linearProfiles), psi0);
[Kbc, rhsLinearBc] = apply_dirichlet(meshData, K, rhsLinear, 0);
psiDirect = Kbc\rhsLinearBc;
linearAgreement = norm(psiLinear-psiDirect, inf) ...
                / max(norm(psiDirect, inf), eps);
assert(linearResult.converged && linearAgreement < 1e-12, ...
    'Picard did not reproduce the direct constant-source solution.');

% Nonlinear normalized profiles exercise dynamic psiAxis updates.
nonlinearProfiles = make_profiles(struct( ...
    'pprime', struct('type', 'normalized-power', ...
        'axisValue', -8e5, 'exponent', 2), ...
    'FFprime', struct('type', 'normalized-power', ...
        'axisValue', -0.8, 'exponent', 1)));
nonlinearOptions = struct( ...
    'tolerance', 2e-8, 'residualTolerance', 2e-8, ...
    'maxIterations', 300, 'omega', 0.45, ...
    'boundaryValue', 0, 'axisMode', 'min', ...
    'updateFluxAxis', true, 'verbose', false);
[psiNonlinear, nonlinearResult] = solve_picard( ...
    meshData, nonlinearProfiles, psi0, nonlinearOptions);
assert(nonlinearResult.converged, 'Nonlinear Picard verification failed.');
assert(max(abs(psiNonlinear(meshData.boundaryNodes))) == 0, ...
    'Nonlinear solution violates the fixed LCFS value.');

% Geometry continuation uses transferred solutions across changing meshes.
startParams = struct( ...
    'A', 3.0, 'B', 0.9, 'C', 0.0, ...
    'G', 1.1, 'H', 0.0, 'nBoundary', 96);
targetParams = struct( ...
    'A', 3.0, 'B', 0.9, 'C', 0.34, ...
    'G', 1.1, 'H', 0.10, 'nBoundary', 120);
continuationOptions = struct();
continuationOptions.mesh = struct('targetH', 0.16);
continuationOptions.initialGuess = struct('axisValue', -1);
continuationOptions.picard = nonlinearOptions;
continuationOptions.verbose = false;
continuation = solve_continuation( ...
    startParams, targetParams, [0, 0.5, 1], ...
    nonlinearProfiles, continuationOptions);
continuationConverged = all(arrayfun( ...
    @(step) step.solver.converged, continuation.steps));
assert(continuationConverged, ...
    'One or more continuation steps failed to converge.');
assert(continuation.finalGeometry.isConcave, ...
    'The final continuation geometry must be concave.');

report = struct();
report.nNodes = meshData.nNodes;
report.initialAxisValue = initialInfo.axisValue;
report.linearIterations = linearResult.nIterations;
report.linearAgreement = linearAgreement;
report.nonlinearIterations = nonlinearResult.nIterations;
report.nonlinearResidual = nonlinearResult.finalResidual;
report.nonlinearAxisValue = nonlinearResult.axisValue;
report.continuationSteps = numel(continuation.steps);
report.continuationFinalResidual = ...
    continuation.finalSolver.finalResidual;
report.continuationFinalConcave = ...
    continuation.finalGeometry.isConcave;

fprintf(['Solver verification: linear agreement=%.3e, nonlinear iters=%d, ' ...
         'nonlinear residual=%.3e, continuation steps=%d\n'], ...
    report.linearAgreement, report.nonlinearIterations, ...
    report.nonlinearResidual, report.continuationSteps);
fprintf('solver verification passed.\n');

if doPlot
    figure('Name', 'Fixed-boundary Picard solver verification', 'Color', 'w');
    subplot(1,2,1)
    trisurf(meshData.elements, meshData.nodes(:,1), ...
        meshData.nodes(:,2), psiNonlinear, 'EdgeColor', 'none');
    view(2)
    axis equal tight
    colorbar
    xlabel('R')
    ylabel('Z')
    title('Nonlinear fixed-boundary \psi')

    subplot(1,2,2)
    semilogy(1:nonlinearResult.nIterations, ...
        nonlinearResult.updateHistory, '-', 'LineWidth', 1.5)
    hold on
    semilogy(1:nonlinearResult.nIterations, ...
        nonlinearResult.residualHistory, '--', 'LineWidth', 1.5)
    hold off
    grid on
    xlabel('Picard iteration')
    ylabel('Relative measure')
    legend('iterate update', 'equation residual', 'Location', 'best')
    title('Picard convergence')
end

end
