%% test_pq_route_comparison.m
% Lightweight checks for the mode-1/mode-3 comparison figure.

clearvars;
close all;
clc;

thisDirectory = fileparts(mfilename('fullpath'));
rootDirectory = fullfile(thisDirectory,'..','..');
addpath(rootDirectory);
setup_solve_GS;

%% Five-node P1 mesh with one interior vertex
point = [ ...
    2, -1; ...
    4, -1; ...
    4,  1; ...
    2,  1; ...
    3,  0];

element = [ ...
    1,2,5; ...
    2,3,5; ...
    3,4,5; ...
    4,1,5];

mesh = struct();
mesh.P1points = point;
mesh.P1elements = element;
mesh.vertices = (1:5).';
mesh.boundaryEdges = [1,2;2,3;3,4;4,1];

psiN = linspace(0,1,51).';

equilibriumMode1 = make_equilibrium( ...
    mesh,[1;1;1;1;0],[3,0],psiN,0.00);

equilibriumMode3 = make_equilibrium( ...
    mesh,[1;1;1;1;0.01],[3.01,0],psiN,0.01);

comparison = plot_pq_route_comparison( ...
    equilibriumMode1,equilibriumMode3, ...
    struct('visible','off','gridSize',80));

assert(isgraphics(comparison.figure,'figure'), ...
    'TEST_PQ_COMPARISON:Figure', ...
    'The comparison routine did not return a valid figure.');

assert(numel(comparison.axes) == 6 && ...
        all(isgraphics(comparison.axes,'axes')), ...
    'TEST_PQ_COMPARISON:TileCount', ...
    'The comparison figure does not contain six panels.');

metricValues = [ ...
    comparison.metrics.psiNRootMeanSquare, ...
    comparison.metrics.psiNMaximum, ...
    comparison.metrics.qRelativeRootMeanSquare, ...
    comparison.metrics.qRelativeMaximum, ...
    comparison.metrics.FRelativeL2, ...
    comparison.metrics.FFprimeRelativeL2];

assert(all(isfinite(metricValues)), ...
    'TEST_PQ_COMPARISON:FiniteMetrics', ...
    'The comparison routine returned a non-finite metric.');

assert(comparison.metrics.psiNRootMeanSquare > 0, ...
    'TEST_PQ_COMPARISON:PsiDifference', ...
    'The synthetic normalized-flux difference was not detected.');

close(comparison.figure);

fprintf('p-q route comparison plot tests passed.\n');


function equilibrium = make_equilibrium( ...
    mesh,psiNNode,axisPoint,profilePsiN,perturbation)
%MAKE_EQUILIBRIUM Construct a minimal finalized-equilibrium fixture.

    q = 1+2*profilePsiN;
    F = 9-0.2*(1-profilePsiN).^2;
    FFprime = 0.2*(1-profilePsiN);

    equilibrium = struct();
    equilibrium.mesh = mesh;
    equilibrium.psiN = psiNNode;
    equilibrium.axisPoint = axisPoint;
    equilibrium.profile = struct();
    equilibrium.profile.psiN = profilePsiN;
    equilibrium.profile.q = q.*(1+perturbation*profilePsiN);
    equilibrium.profile.Fpol = F.*(1-0.1*perturbation*profilePsiN);
    equilibrium.profile.Gpol = equilibrium.profile.Fpol.^2;
    equilibrium.profile.FdF_dpsiN = ...
        FFprime.*(1+0.2*perturbation*profilePsiN);
end
