function report = verify_local_surface_bundle(equilibrium,doPlot)
%VERIFY_LOCAL_SURFACE_BUNDLE Verify stage-1 local surface extraction.

narginchk(1,2);
if nargin<2
    doPlot = true;
end
if ~isstruct(equilibrium) || ~isscalar(equilibrium) || ...
        ~all(isfield(equilibrium,{'mesh','psi','axis'}))
    error('GS:ballooning:InvalidEquilibrium', ...
        'Run main_cos and pass its equilibrium struct.');
end

psiN = (0.55:0.10:0.95).';
bundle = extract_local_surface_bundle( ...
    equilibrium.mesh,equilibrium.psi,equilibrium.axis,psiN, ...
    struct('nPoloidal',512,'boundaryValue',0));

assert(bundle.nSurface==5,'Five radial surfaces are required.');
assert(bundle.nPoloidal==512,'Unexpected poloidal resolution.');
assert(bundle.diagnostics.areasStrictlyIncreasing, ...
    'Surface areas are not nested monotonically.');
assert(bundle.diagnostics.allEncloseAxis, ...
    'A surface does not enclose the magnetic axis.');
assert(bundle.diagnostics.maximumFluxError<1e-10, ...
    'Resampled points have excessive P1 flux error.');
assert(bundle.diagnostics.maximumRelativeChordVariation<0.03, ...
    'Geometric arclength sampling is unexpectedly nonuniform.');
assert(bundle.diagnostics.allStartAtAxisHeight<1e-12, ...
    'A surface does not start at the magnetic-axis height.');
assert(all(strcmp({bundle.surfaces.orientation},'counterclockwise')), ...
    'The verified surfaces must use counterclockwise orientation.');
assert(all(arrayfun(@(surface) surface.Z(2)>surface.Z(1), ...
    bundle.surfaces)),'Every surface must move upward from its start.');

report = struct();
report.psiN = bundle.psiN;
report.areas = [bundle.surfaces.area].';
report.perimeters = [bundle.surfaces.perimeter].';
report.outboardMidplaneR = ...
    [bundle.surfaces.outboardMidplaneR].';
report.inboardMidplaneR = ...
    [bundle.surfaces.inboardMidplaneR].';
report.maximumFluxError = bundle.diagnostics.maximumFluxError;
report.maximumRelativeChordVariation = ...
    bundle.diagnostics.maximumRelativeChordVariation;
report.rawPointCounts = arrayfun( ...
    @(surface) size(surface.rawPoints,1),bundle.surfaces);
report.maximumRawSegmentLength = arrayfun(@(surface) max(sqrt(sum( ...
    diff([surface.rawPoints;surface.rawPoints(1,:)],1,1).^2,2))), ...
    bundle.surfaces);
report.bundle = bundle;

fprintf(['Local-surface verification: surfaces=%d, Ntheta=%d, ' ...
         'max |delta psi|=%.3e, max chord CV=%.3e, ' ...
         'raw points=%d--%d\n'], ...
    bundle.nSurface,bundle.nPoloidal,report.maximumFluxError, ...
    report.maximumRelativeChordVariation,min(report.rawPointCounts), ...
    max(report.rawPointCounts))
fprintf('local flux-surface geometry verification passed.\n')

if doPlot
    plot_local_surface_bundle(bundle);
end
end
