function report = verify_local_ballooning_coefficients(input,doPlot)
%VERIFY_LOCAL_BALLOONING_COEFFICIENTS Verify the stage-3 PEST coefficients.
%
%   REPORT = VERIFY_LOCAL_BALLOONING_COEFFICIENTS(EQUILIBRIUM,TRUE)
%   builds stages 1 and 2 from the main_cos result. A previously built
%   localEq may also be supplied to avoid repeating those two stages.

narginchk(1,2);
if nargin<2
    doPlot = true;
end
if isstruct(input) && all(isfield(input,{'map','eqfunc','bundle'}))
    localEq = input;
else
    equilibrium = input;
    bundle = extract_local_surface_bundle( ...
        equilibrium.mesh,equilibrium.psi,equilibrium.axis, ...
        (0.55:0.05:0.95).', ...
        struct('nPoloidal',512,'boundaryValue',0));
    localEq = build_local_pest_equilibrium( ...
        equilibrium,bundle,struct('nTheta',512));
end

localBal = build_local_ballooning_coefficients( ...
    localEq,0.75,struct( ...
        'theta0',0,'nPeriods',1,'poloidalModeCutoff',24));
d = localBal.diagnostics;

assert(d.allMetricJacobiansPositive, ...
    'A normalized PEST metric Jacobian is non-positive.');
assert(d.targetMetricDeterminantRelativeRms<1e-9, ...
    'det(g_ij)=Jacobian^2 is not satisfied.');
assert(d.targetJacobianAnalyticRelativeRms<0.15, ...
    'The geometric and q*R^2/F PEST Jacobians disagree excessively.');
assert(d.targetGradPsiMetricRelativeRms<0.15, ...
    '|grad psi|^2 from the metric and FEM field disagree excessively.');
assert(d.targetB2MetricRelativeRms<0.15, ...
    'Direct and metric magnetic-field magnitudes disagree excessively.');
assert(d.maximumMapRegularizationDisplacement<0.02, ...
    'Poloidal regularization moved a flux surface by more than 2 cm.');
assert(d.targetFilteredB2ChangeRelativeRms<0.05, ...
    'Poloidal regularization changed B^2 by more than 5 percent RMS.');
assert(d.extendedFOverGIdentityRelativeError<1e-9, ...
    'The coefficient identity f/g=Jacobian^2 failed.');
assert(d.qprimeNormalizationRelativeError<1e-10, ...
    'qprime was not converted to normalized flux consistently.');
assert(d.pprimeNormalizationRelativeError<1e-12, ...
    'pprime was not converted to normalized pressure consistently.');
assert(d.minimumK>0 && d.minimumG>0 && d.minimumF>0, ...
    'K, g, and f must remain positive.');
assert(d.allCoefficientsFinite, ...
    'A ballooning coefficient is non-finite.');

report = struct('localEquilibrium',localEq, ...
    'localBallooning',localBal,'diagnostics',d);

fprintf(['Ballooning coefficient target: psiN=%.2f, q=%.8g, ' ...
         'sHat=%.8g, alpha=%.8g\n'], ...
    localBal.targetPsiN,localBal.physicalReference.q, ...
    localBal.physicalReference.sHat,localBal.physicalReference.alpha)
fprintf(['Normalization: aN=%.8g m, BN=%.8g T, ' ...
         'qprime_bar=%.8g, pprime_bar=%.8g\n'], ...
    localBal.normalization.aN,localBal.normalization.BN, ...
    localBal.coefficients.qprime,localBal.coefficients.pprime)
fprintf(['Metric diagnostics: J analytic RMS=%.3e, ' ...
         '|grad psi|^2 RMS=%.3e, B^2 RMS=%.3e\n'], ...
    d.targetJacobianAnalyticRelativeRms, ...
    d.targetGradPsiMetricRelativeRms,d.targetB2MetricRelativeRms)
fprintf(['Mesh-scale filtering: max surface shift=%.3e m, ' ...
         'RMS surface shift=%.3e m, target B^2 change=%.3e\n'], ...
    d.maximumMapRegularizationDisplacement, ...
    d.rmsMapRegularizationDisplacement, ...
    d.targetFilteredB2ChangeRelativeRms)
fprintf(['Coefficient ranges: min(K)=%.3e, min(g)=%.3e, ' ...
         'min(f)=%.3e, max|c|=%.3e\n'], ...
    d.minimumK,d.minimumG,d.minimumF,d.maximumAbsC)
fprintf('local ballooning-coefficient verification passed.\n')

if doPlot
    plot_local_ballooning_coefficients(localBal);
end
end
