function report = verify_local_salpha_scan(input,doPlot)
%VERIFY_LOCAL_SALPHA_SCAN Verify mappings, polynomial basis, and scan.

narginchk(1,2);
if nargin<2
    doPlot = true;
end
if isstruct(input) && all(isfield(input,{'map','eqfunc','bundle'}))
    localEq = input;
else
    equilibrium = input;
    bundle = extract_local_surface_bundle( ...
        equilibrium.mesh,equilibrium.psi,equilibrium.axis, ...
        (0.55:0.05:0.95).', ...
        struct('nPoloidal',512,'boundaryValue',0));
    localEq = build_local_pest_equilibrium( ...
        equilibrium,bundle,struct('nTheta',512));
end

targetPsiN = 0.75;
model = prepare_local_salpha_model(localEq,targetPsiN, ...
    struct('nPeriods',6,'poloidalModeCutoff',24));
reference = evaluate_local_salpha_coefficients(model, ...
    model.reference.sHat,model.reference.alpha,0);
base = model.base.coefficients;
referenceErrors = struct( ...
    'g',relative_rms(reference.g,base.g), ...
    'c',relative_rms(reference.c,base.c), ...
    'f',relative_rms(reference.f,base.f), ...
    'qprime',model.reference.qprimeRelativeError, ...
    'pprime',model.reference.pprimeRelativeError);

theta0Test = 0.37;
sTest = 1.35;
alphaTest = 0.85;
basis = assemble_local_salpha_phase_basis(model,theta0Test,64);
direct = evaluate_local_salpha_coefficients( ...
    model,sTest,alphaTest,theta0Test);
directG = interp1(direct.theta,direct.g,basis.thetaGrid,'pchip');
directC = interp1(direct.theta,direct.c,basis.thetaGrid,'pchip');
directF = interp1(direct.theta,direct.f,basis.thetaGrid,'pchip');
b = basis.coefficients;
reconstructedG = b.g0+sTest*b.gS+sTest^2*b.gSS;
reconstructedC = alphaTest*b.cA+alphaTest^2*b.cAA ...
    +sTest*alphaTest*b.cSA;
reconstructedF = b.f0+sTest*b.fS+sTest^2*b.fSS;
polynomialErrors = struct( ...
    'g',relative_rms(reconstructedG,directG), ...
    'c',relative_rms(reconstructedC,directC), ...
    'f',relative_rms(reconstructedF,directF));

sHatValues = unique([linspace(0,4,17),model.reference.sHat]);
alphaValues = unique([linspace(0,4,17),model.reference.alpha]);
scan = scan_local_salpha_diagram(localEq,targetPsiN,struct( ...
    'sHatValues',sHatValues, ...
    'alphaValues',alphaValues, ...
    'nTheta0',8,'nPeriods',6,'elementsPerPeriod',64, ...
    'poloidalModeCutoff',24,'eigenTolerance',1e-12, ...
    'maxIterations',3000,'verbose',true));
[~,referenceSIndex] = min(abs(scan.sHat-model.reference.sHat));
[~,referenceAlphaIndex] = min(abs( ...
    scan.alpha-model.reference.alpha));
referenceLambdaMax = scan.lambdaMax( ...
    referenceSIndex,referenceAlphaIndex);

phaseAlphaValues = unique([0,model.reference.alpha,1,1.5,2,3,4]);
phaseScan = scan_local_salpha_diagram(localEq,targetPsiN,struct( ...
    'sHatValues',model.reference.sHat, ...
    'alphaValues',phaseAlphaValues, ...
    'nTheta0',16,'nPeriods',6,'elementsPerPeriod',64, ...
    'poloidalModeCutoff',24,'eigenTolerance',1e-12, ...
    'maxIterations',3000,'verbose',false));
coarsePhaseValues = zeros(size(phaseAlphaValues));
for k = 1:numel(phaseAlphaValues)
    [~,alphaIndex] = min(abs(scan.alpha-phaseAlphaValues(k)));
    coarsePhaseValues(k) = scan.lambdaMax(referenceSIndex,alphaIndex);
end
theta0ConvergenceError = max(abs( ...
    phaseScan.lambdaMax(:)-coarsePhaseValues(:)));

referenceShearLambda = scan.lambdaMax(referenceSIndex,:);
crossingIndex = find(referenceShearLambda(1:end-1)<=0 ...
    & referenceShearLambda(2:end)>0,1,'first');
if isempty(crossingIndex)
    criticalAlpha = NaN;
else
    x1 = scan.alpha(crossingIndex);
    x2 = scan.alpha(crossingIndex+1);
    y1 = referenceShearLambda(crossingIndex);
    y2 = referenceShearLambda(crossingIndex+1);
    criticalAlpha = x1-y1*(x2-x1)/(y2-y1);
end

fprintf(['s-alpha reference errors: g=%.3e, c=%.3e, f=%.3e, ' ...
         'qprime=%.3e, pprime=%.3e\n'], ...
    referenceErrors.g,referenceErrors.c,referenceErrors.f, ...
    referenceErrors.qprime,referenceErrors.pprime)
fprintf('Polynomial basis errors: g=%.3e, c=%.3e, f=%.3e\n', ...
    polynomialErrors.g,polynomialErrors.c,polynomialErrors.f)
fprintf(['Scan diagnostics: lambda=[%.6g, %.6g], unstable share=%.3f, ' ...
         'max residual=%.3e, elapsed=%.1f s\n'], ...
    scan.diagnostics.minimumLambda,scan.diagnostics.maximumLambda, ...
    scan.diagnostics.unstableFraction, ...
    scan.diagnostics.maximumResidual,scan.elapsedSeconds)
fprintf('Exact GS reference point: max_theta0(lambda)=%.9g\n', ...
    referenceLambdaMax)
fprintf(['theta0 convergence (8 vs 16 phases): max |Delta lambda|=' ...
         '%.3e, critical alpha at reference shear=%.6g\n'], ...
    theta0ConvergenceError,criticalAlpha)

assert(max(struct2array(referenceErrors))<1e-6, ...
    'The s-alpha reference point does not reproduce the equilibrium.');
assert(max(struct2array(polynomialErrors))<1e-10, ...
    'The polynomial scan basis does not reproduce direct coefficients.');
assert(scan.diagnostics.nFailed==0, ...
    'At least one s-alpha eigenvalue solve failed.');
assert(scan.diagnostics.maximumResidual<1e-6, ...
    'A scan eigenvalue residual is too large.');
assert(all(scan.lambdaMax(:,1)<0), ...
    'The alpha=0 column must contain no pressure-driven instability.');
assert(any(scan.lambdaMax(:)>0) && any(scan.lambdaMax(:)<0), ...
    'The selected scan domain must contain both stable and unstable points.');
assert(referenceLambdaMax<0, ...
    'The exact GS reference point was expected to remain stable.');
assert(theta0ConvergenceError<1e-2, ...
    'The eight-phase theta0 maximization is not sufficiently converged.');
assert(isfinite(criticalAlpha), ...
    'No marginal alpha crossing was found at the reference shear.');

report = struct('localEquilibrium',localEq,'model',model, ...
    'scan',scan,'referenceErrors',referenceErrors, ...
    'polynomialErrors',polynomialErrors, ...
    'referenceLambdaMax',referenceLambdaMax, ...
    'theta0ConvergenceError',theta0ConvergenceError, ...
    'criticalAlphaAtReferenceShear',criticalAlpha);

fprintf('local s-alpha scan verification passed.\n')

if doPlot
    plot_local_salpha_diagram(scan);
end
end


function value = relative_rms(actual,expected)
value = sqrt(mean((actual(:)-expected(:)).^2)) ...
    /max(sqrt(mean(expected(:).^2)),eps);
end
