function report = verify_local_pest_equilibrium(equilibrium,doPlot)
%VERIFY_LOCAL_PEST_EQUILIBRIUM Verify local q and PEST construction.

narginchk(1,2);
if nargin<2
    doPlot = true;
end
if exist('extract_local_surface_bundle','file')~=2
    error('GS:ballooning:MissingStage1', ...
        'Add the GS_fixed/ballooning folder to the MATLAB path.');
end

bundle = extract_local_surface_bundle( ...
    equilibrium.mesh,equilibrium.psi,equilibrium.axis, ...
    (0.55:0.05:0.95).',struct('nPoloidal',512,'boundaryValue',0));
localEq = build_local_pest_equilibrium( ...
    equilibrium,bundle,struct('nTheta',512));

diagnostics = localEq.diagnostics;
assert(diagnostics.allPESTAnglesMonotone, ...
    'A PEST angle is not strictly monotone.');
assert(diagnostics.maximumStraightFieldLineError<1e-10, ...
    'PEST field-line straightness verification failed.');
assert(diagnostics.maximumQIntegralRelativeError<5e-3, ...
    ['The point-left and segment-trapezoid q contour integrals differ ' ...
     'excessively.']);
assert(diagnostics.minimumJacobian>0, ...
    'The PEST Jacobian must remain positive.');
assert(diagnostics.contravariantIdentityError<1e-12, ...
    'q/J=F/R^2 is not satisfied.');
assert(diagnostics.maximumNormalizedMapFluxError<3e-3, ...
    'Uniform PEST remapping moved too far off its flux surface.');
assert(all(isfinite(localEq.profiles.q)) && all(localEq.profiles.q>0), ...
    'The q profile must be finite and positive.');
assert(all(isfinite(localEq.profiles.sHat)), ...
    'Magnetic shear is non-finite.');
assert(all(isfinite(localEq.profiles.alpha)), ...
    'Reference alpha is non-finite.');
assert(any(abs(localEq.profiles.psiN-0.75)<1e-13), ...
    'The intended local target psiN=0.75 is absent.');

report = struct();
report.profiles = localEq.profiles;
report.diagnostics = diagnostics;
report.localEquilibrium = localEq;

fprintf(['Local PEST verification: q=[%.6g, %.6g], ' ...
         'sHat=[%.6g, %.6g], alpha=[%.6g, %.6g]\n'], ...
    min(localEq.profiles.q),max(localEq.profiles.q), ...
    min(localEq.profiles.sHat),max(localEq.profiles.sHat), ...
    min(localEq.profiles.alpha),max(localEq.profiles.alpha))
fprintf(['PEST diagnostics: straightness=%.3e, map flux error=%.3e, ' ...
         'Jacobian=[%.6g, %.6g]\n'], ...
    diagnostics.maximumStraightFieldLineError, ...
    diagnostics.maximumNormalizedMapFluxError, ...
    diagnostics.minimumJacobian,diagnostics.maximumJacobian)
fprintf('local PEST equilibrium verification passed.\n')

if doPlot
    plot_local_pest_equilibrium(localEq);
end
end
