function report = verify_miller_gs_salpha(equilibrium,doPlot)
%VERIFY_MILLER_GS_SALPHA Verify Miller-boundary GS and s-alpha pipeline.

narginchk(1,2);
if nargin<2
    doPlot = true;
end
required = {'geometry','mesh','psi','axis','topology', ...
    'solver','millerShape'};
if ~isstruct(equilibrium) || ~isscalar(equilibrium) || ...
        ~all(isfield(equilibrium,required)) || ...
        ~strcmp(equilibrium.geometry.type,'miller-d')
    error('GS:ballooning:InvalidMillerEquilibrium', ...
        'equilibrium must be the completed result from main_miller.');
end

shape = equilibrium.millerShape;
assert(abs(shape.aspectRatio-3.17)<1e-12, ...
    'The Miller boundary aspect ratio differs from 3.17.');
assert(abs(shape.kappa-1.66)<1e-12, ...
    'The Miller boundary elongation differs from 1.66.');
assert(abs(shape.delta-0.416)<1e-12, ...
    'The Miller boundary triangularity differs from 0.416.');
assert(equilibrium.topology.passed && ...
       equilibrium.topology.nOPoints==1 && ...
       equilibrium.topology.nXPoints==0, ...
    'The Miller GS equilibrium must have one O-point and no X-point.');
assert(equilibrium.solver.converged && ...
       equilibrium.solver.finalResidual<2e-8, ...
    'The Miller nonlinear GS solve did not meet its residual target.');

salpha = verify_local_salpha_scan(equilibrium,doPlot);
localEq = salpha.localEquilibrium;
d = localEq.diagnostics;
assert(d.allPESTAnglesMonotone, ...
    'A Miller PEST angle is not monotone.');
assert(d.maximumStraightFieldLineError<1e-10, ...
    'Miller PEST straight-field-line verification failed.');
assert(d.maximumNormalizedMapFluxError<3e-3, ...
    'The Miller PEST map moved too far off a flux surface.');
assert(d.minimumJacobian>0, ...
    'The Miller PEST Jacobian is non-positive.');

targetIndex = find(abs(localEq.profiles.psiN-0.75)<1e-12,1);
surface = localEq.bundle.surfaces(targetIndex);
[localShape,shapeDiagnostics] = measure_miller_surface(surface);

report = struct();
report.equilibrium = equilibrium;
report.localEquilibrium = localEq;
report.salpha = salpha;
report.boundaryShape = shape;
report.localShape = localShape;
report.shapeDiagnostics = shapeDiagnostics;
report.pestDiagnostics = d;

fprintf(['Miller GS verification: nodes=%d, elements=%d, residual=%.3e, ' ...
         'axis=(%.6f,%.6f)\n'], ...
    equilibrium.mesh.nNodes,equilibrium.mesh.nElements, ...
    equilibrium.solver.finalResidual, ...
    equilibrium.axis.R,equilibrium.axis.Z)
fprintf(['Target surface psiN=0.75: R0=%.6f, a=%.6f, ' ...
         'kappa=%.6f, delta=%.6f\n'], ...
    localShape.R0,localShape.a,localShape.kappa,localShape.delta)
fprintf(['Local reference: q=%.6f, sHat=%.6f, alpha=%.6f, ' ...
         'critical alpha=%.6f\n'], ...
    localEq.profiles.q(targetIndex), ...
    localEq.profiles.sHat(targetIndex), ...
    localEq.profiles.alpha(targetIndex), ...
    salpha.criticalAlphaAtReferenceShear)
fprintf(['PEST diagnostics: straightness=%.3e, flux error=%.3e, ' ...
         'Jacobian min=%.6g\n'], ...
    d.maximumStraightFieldLineError, ...
    d.maximumNormalizedMapFluxError,d.minimumJacobian)
fprintf('Miller GS-to-s-alpha validation passed.\n')

if doPlot
    plot_local_pest_equilibrium(localEq);
end
end


function [shape,diagnostics] = measure_miller_surface(surface)
R = surface.R(:);
Z = surface.Z(:);
[Rout,outIndex] = max(R);
[Rin,inIndex] = min(R);
[Ztop,topIndex] = max(Z);
R0 = 0.5*(Rout+Rin);
a = 0.5*(Rout-Rin);
shape = struct('R0',R0,'a',a,'aspectRatio',R0/a, ...
    'kappa',Ztop/a,'delta',(R0-R(topIndex))/a, ...
    'Rout',Rout,'Rin',Rin,'Rtop',R(topIndex),'Ztop',Ztop);
diagnostics = struct( ...
    'outboardAbsZ',abs(Z(outIndex)), ...
    'inboardAbsZ',abs(Z(inIndex)), ...
    'topIndex',topIndex);
end
