%% test_pq_route_consistency.m
% End-to-end route-consistency test:
%
%   Route 1:
%       prescribed pprime and FFprime
%           -> profile mode 1
%           -> reference equilibrium and q
%
%   Route 2:
%       prescribed pprime and q from Route 1
%           -> profile mode 3
%           -> reconstructed G and FFprime
%           -> recovered equilibrium
%
% This test checks:
%
%   - solve_GS mode dispatch
%   - p-q outer iteration
%   - G = F^2 reconstruction
%   - FFprime = 0.5*dG/dpsiN
%   - q = F*qPerF
%   - fixed-Fb normalization
%   - finalize_GS_equilibrium output consistency
%   - visual route comparison of flux surfaces and source profiles
%
% Solver convention:
%
%   psiN = 0 at the magnetic axis
%   psiN = 1 at the fixed boundary
%
%   pprime and FFprime are derivatives with respect to psiN.

clearvars;
close all;
clc;

%% Repository setup
thisDirectory = fileparts(mfilename('fullpath'));
rootDirectory = fullfile(thisDirectory, '..', '..');

addpath(rootDirectory);

setup_solve_GS;

%% Route-consistency tolerances
%
% qConstraintMax and qConstraintRms should be comparable to the requested
% p-q outer tolerances.
%
% FFprime is recovered from a low-order direct-FFprime inverse model.

tolerance = struct();

tolerance.boundary = 1.0e-13;

tolerance.qConstraintMax = 2.0e-3;
tolerance.qConstraintRmsLog = 1.0e-3;

tolerance.qContourRms = 3.0e-3;
tolerance.qContourMax = 6.0e-3;

tolerance.psiRelativeL2 = 1.0e-2;
tolerance.psiNRootMeanSquare = 5.0e-3;

tolerance.FRelativeL2 = 5.0e-3;
tolerance.GRelativeL2 = 1.0e-2;
tolerance.FFprimeRelativeL2 = 1.5e-1;

tolerance.axisPosition = 3.0e-2;
tolerance.axisFluxRelative = 1.0e-2;

tolerance.IpRelative = 1.0e-2;
tolerance.volumeRelative = 1.0e-12;

tolerance.pressureRelativeInfinity = 1.0e-12;

%% Miller boundary
R0 = 3.0;
aMinor = 0.8;

kappa = 1.5;
delta = -0.4;

B0 = 3.0;

pedge = 0.0;
psiBoundary = 0.0;

% Moderate resolution suitable for an integration test.
nBoundary = 180;
NR = 96;
NZ = 112;

nProfile = 101;
quadratureDegree = 10;

theta = ...
    (0:nBoundary-1).'*(2*pi/nBoundary);

triangularityAngle = asin(delta);

RBoundary = ...
    R0 + aMinor*cos( ...
        theta + triangularityAngle*sin(theta));

ZBoundary = ...
    kappa*aMinor*sin(theta);

if any(RBoundary <= 0)
    error('TEST_PQ_ROUTE:InvalidBoundary', ...
        'The Miller boundary contains R <= 0.');
end

%% Reference pprime and FFprime profiles
psiNProfile = ...
    linspace(0, 1, nProfile).';

% Pressure derivative:
%
%   pprime(psiN) = pprime0*(1-psiN^aP)^bP

pprime0 = -1.0e6;
aP = 1.5;
bP = 2.0;

pprime = ...
    pprime0*(1-psiNProfile.^aP).^bP;

% Use the same generalized-parabola family as pprime.  For aF=bF=2 this
% profile is quartic, so four reduced modes are required for exact
% representation when every basis function contains the edge factor 1-s.
%
%   FFprime(psiN) = FFprime0*(1-psiN^aF)^bF

FFprime0 = 3.0;
aF = 1.5;
bF = 2.0;
nFFprimeBasis = 4;

FFprime = ...
    FFprime0*(1-psiNProfile.^aF).^bF;

referenceFFprimeBasis = construct_FFprime_basis( ...
    psiNProfile,nFFprimeBasis,true);

referenceFFprimeCoefficients = ...
    referenceFFprimeBasis\FFprime;

leadingFFprimeCoefficient = ...
    referenceFFprimeBasis(:,1)\FFprime;

leadingFFprimeApproximation = ...
    referenceFFprimeBasis(:,1)*leadingFFprimeCoefficient;

referenceCurvedFraction = norm( ...
    FFprime-leadingFFprimeApproximation) ...
    /max(norm(FFprime),eps);

referenceBasisError = norm( ...
    FFprime-referenceFFprimeBasis*referenceFFprimeCoefficients) ...
    /max(norm(FFprime),eps);

assert(referenceCurvedFraction > 5.0e-2, ...
    'TEST_PQ_ROUTE:InsufficientReferenceCurvature', ...
    ['The reference FFprime differs from its best leading-basis ', ...
     'approximation by only %.3e.'],referenceCurvedFraction);

assert(referenceBasisError < 2.0e-2, ...
    'TEST_PQ_ROUTE:ReferenceOutsideReducedBasis', ...
    ['The selected FFprime has a %.3e relative projection error in ', ...
     'the selected inverse basis. Increase nBasis or relax the ', ...
     'expected FFprime recovery accuracy.'],referenceBasisError);

if any(~isfinite(pprime)) || ...
        any(~isfinite(FFprime))
    error('TEST_PQ_ROUTE:InvalidProfiles', ...
        'The reference profiles contain NaN or Inf.');
end

% Verify that the corresponding reference G remains positive.
FboundaryReference = R0*B0;

integrated2FFprime = ...
    cumtrapz(psiNProfile, 2*FFprime);

GReferenceEstimate = ...
    FboundaryReference^2 ...
    + integrated2FFprime ...
    - integrated2FFprime(end);

if any(GReferenceEstimate <= 0)
    error('TEST_PQ_ROUTE:NonpositiveReferenceG', ...
        ['The selected FFprime profile produces nonpositive G. ', ...
         'Reduce FFprime0 or increase B0.']);
end

%% Common solve_GS input
inputCommon = struct();

inputCommon.grid = struct( ...
    'nBoundary', nBoundary, ...
    'NR', NR, ...
    'NZ', NZ, ...
    'quadratureDegree', quadratureDegree, ...
    'nProfile', nProfile);

inputCommon.dim = struct( ...
    'R0', R0, ...
    'B0', B0, ...
    'aMinor', aMinor);

inputCommon.boundary = struct( ...
    'R', RBoundary, ...
    'Z', ZBoundary, ...
    'psiBoundary', psiBoundary);

inputCommon.Picard = struct( ...
    'omega', 0.5, ...
    'maxIterations', 120, ...
    'updateTolerance', 1.0e-9, ...
    'residualTolerance', 1.0e-9, ...
    'axisMode', 'auto', ...
    'symmetryTolerance', 1.0e-12, ...
    'fluxSpanTolerance', 1.0e-12);

% Disable plotting and verbose output in automated integration tests.
inputCommon.output = struct( ...
    'verbose', true, ...
    'checkTime', true, ...
    'showPlot', true);

%% ================================================================
% Route 1: prescribed pprime and FFprime
% ================================================================
inputMode1 = inputCommon;

inputMode1.profile = struct( ...
    'mode', 1, ...
    'pprime', pprime, ...
    'FFprime', FFprime, ...
    'pedge', pedge);

equilibriumMode1 = ...
    solve_GS(inputMode1);

assert(equilibriumMode1.solverResult.converged, ...
    'TEST_PQ_ROUTE:Mode1Convergence', ...
    'The reference mode-1 Picard solve did not converge.');

assert(equilibriumMode1.solverResult.finalRelativeResidual ...
        < inputMode1.Picard.residualTolerance, ...
    'TEST_PQ_ROUTE:Mode1Residual', ...
    'The reference mode-1 nonlinear residual is too large.');

assert(isfield(equilibriumMode1, 'qResult') && ...
        isfield(equilibriumMode1, 'qGeometry'), ...
    'TEST_PQ_ROUTE:Mode1QOutput', ...
    ['Mode 1 did not return qResult and qGeometry through ', ...
     'finalize_GS_equilibrium.']);

boundaryNodesMode1 = ...
    equilibriumMode1.mesh.boundaryNodes;

boundaryErrorMode1 = norm( ...
    equilibriumMode1.psi(boundaryNodesMode1) ...
    - psiBoundary, inf);

assert(boundaryErrorMode1 < tolerance.boundary, ...
    'TEST_PQ_ROUTE:Mode1Boundary', ...
    'The mode-1 boundary condition is not satisfied.');

%% Prescribed q for Route 2
%
% Use the actual q-evaluation grid rather than the dense output profile.
% This avoids adding an unnecessary dense-grid interpolation round trip.

qTarget = struct();

qTarget.psiN = ...
    equilibriumMode1.qResult.psiN;

qTarget.q = ...
    equilibriumMode1.qResult.q;

assert(all(isfinite(qTarget.psiN)) && ...
       all(isfinite(qTarget.q)), ...
    'TEST_PQ_ROUTE:InvalidQTarget', ...
    'The mode-1 q target contains NaN or Inf.');

assert(all(diff(qTarget.psiN) > 0), ...
    'TEST_PQ_ROUTE:InvalidQTargetGrid', ...
    'The mode-1 q target grid is not strictly increasing.');

%% ================================================================
% Route 2: prescribed pprime and q
% ================================================================
inputMode3 = inputCommon;

inputMode3.profile = struct();

inputMode3.profile.mode = 3;
inputMode3.profile.pprime = pprime;
inputMode3.profile.q = qTarget;
inputMode3.profile.pedge = pedge;

% Mode 1 reconstructs G by fixing F at the boundary. Use exactly the same
% normalization for the reverse p-q route.
inputMode3.profile.normalization = struct();

inputMode3.profile.normalization.mode = ...
    'fixed_Fb';

inputMode3.profile.normalization.Fb = ...
    equilibriumMode1.profile.Fpol(end);

inputMode3.profile.FSign = ...
    sign(equilibriumMode1.profile.Fpol(end));

% Start from the cylindrical predictor rather than the reference FFprime.
% This exercises both the initializer and the actual-GS inverse iteration.
inputMode3.profile.initial = struct();

inputMode3.profile.initial.type = ...
    'cylindrical';

% p-q outer iteration
inputMode3.pqConstraint = struct();

inputMode3.pqConstraint.outer = struct();

inputMode3.pqConstraint.outer.maxIterations = 30;

inputMode3.pqConstraint.outer.qRelativeTolerance = ...
    tolerance.qConstraintMax;

inputMode3.pqConstraint.outer.qRmsLogTolerance = ...
    tolerance.qConstraintRmsLog;

% Force at least one G update so the test cannot pass only because the
% initial constant-G profile happens to fall inside a loose tolerance.
inputMode3.pqConstraint.outer.minimumIterations = 2;

inputMode3.pqConstraint.outer.minimumQPoints = 3;

inputMode3.pqConstraint.outer.stopOnInnerNonconvergence = true;
inputMode3.pqConstraint.outer.errorOnFailure = false;
inputMode3.pqConstraint.outer.storePsiHistory = false;
inputMode3.pqConstraint.outer.verbose = false;

% Direct-FFprime reduced inverse solve
inputMode3.pqConstraint.FFprime = struct();
inputMode3.pqConstraint.FFprime.nBasis = nFFprimeBasis;
inputMode3.pqConstraint.FFprime.regularization = 1.0e-8;
inputMode3.pqConstraint.FFprime.jacobianRidge = 1.0e-12;
inputMode3.pqConstraint.FFprime.initialDamping = 1.0e-3;
inputMode3.pqConstraint.FFprime.maxCoefficientStep = 2.0;
inputMode3.pqConstraint.FFprime.fitRange = [0, 0.95];
inputMode3.pqConstraint.FFprime.axisWeight = 0.25;

equilibriumMode3 = ...
    solve_GS(inputMode3);

%% Mode-3 convergence and output-contract checks
assert(isfield(equilibriumMode3, 'constraintResult'), ...
    'TEST_PQ_ROUTE:MissingConstraintResult', ...
    'Mode 3 did not return equilibrium.constraintResult.');

assert(isfield(equilibriumMode3, 'FFprimeModel'), ...
    'TEST_PQ_ROUTE:MissingFFprimeModel', ...
    'Mode 3 did not return equilibrium.FFprimeModel.');

assert(isfield(equilibriumMode3.profile, 'qPrescribed'), ...
    'TEST_PQ_ROUTE:MissingPrescribedQ', ...
    'Mode 3 did not return equilibrium.profile.qPrescribed.');

assert(equilibriumMode3.solverResult.converged, ...
    'TEST_PQ_ROUTE:Mode3InnerConvergence', ...
    'The final mode-3 inner Picard solve did not converge.');

assert(equilibriumMode3.constraintResult.converged, ...
    'TEST_PQ_ROUTE:Mode3OuterConvergence', ...
    ['The mode-3 p-q outer iteration did not converge. ', ...
     'Termination reason: %s.'], ...
    equilibriumMode3.constraintResult.terminationReason);

assert(equilibriumMode3.profile.mode == 3, ...
    'TEST_PQ_ROUTE:Mode3OutputMode', ...
    'The finalized equilibrium did not preserve profile mode 3.');

assert(equilibriumMode3.constraintResult.outerIterations >= 2, ...
    'TEST_PQ_ROUTE:OuterIterationNotExercised', ...
    'The route test did not exercise an FFprime coefficient update.');

coefficientStepHistory = ...
    equilibriumMode3.constraintResult.history.coefficientStep;

finiteCoefficientStep = ...
    coefficientStepHistory(isfinite(coefficientStepHistory));

assert(~isempty(finiteCoefficientStep) && ...
       any(finiteCoefficientStep > 100*eps), ...
    'TEST_PQ_ROUTE:ZeroFFprimeUpdate', ...
    'The mode-3 route did not apply a nonzero FFprime update.');

recoveredFFprimeBasis = construct_FFprime_basis( ...
    equilibriumMode3.profile.psiN, ...
    equilibriumMode3.FFprimeModel.nBasis, ...
    equilibriumMode3.FFprimeModel.enforceZeroEdge);

recoveredFFprime = equilibriumMode3.profile.FdF_dpsiN(:);

recoveredLeadingCoefficient = ...
    recoveredFFprimeBasis(:,1)\recoveredFFprime;

recoveredCurvedFraction = norm( ...
    recoveredFFprime ...
    -recoveredFFprimeBasis(:,1)*recoveredLeadingCoefficient) ...
    /max(norm(recoveredFFprime),eps);

assert(recoveredCurvedFraction > 2.0e-2, ...
    'TEST_PQ_ROUTE:CurvedModeNotRecovered', ...
    ['The recovered FFprime differs from its best leading-basis ', ...
     'approximation by only %.3e.'],recoveredCurvedFraction);

%% Mesh consistency
%
% Both routes use identical geometry and grid inputs, so the generated
% meshes should be identical. A different mesh would make direct nodal
% comparison of psi invalid.

pointsMode1 = equilibriumMode1.mesh.points;
pointsMode3 = equilibriumMode3.mesh.points;

elementsMode1 = equilibriumMode1.mesh.elements;
elementsMode3 = equilibriumMode3.mesh.elements;

assert(isequal(size(pointsMode1), size(pointsMode3)), ...
    'TEST_PQ_ROUTE:MeshPointCount', ...
    'The two routes generated different P3 point counts.');

meshPointDifference = ...
    norm(pointsMode3-pointsMode1, inf);

assert(meshPointDifference < 1.0e-13, ...
    'TEST_PQ_ROUTE:MeshCoordinates', ...
    'The two routes generated different P3 node coordinates.');

assert(isequal(elementsMode1, elementsMode3), ...
    'TEST_PQ_ROUTE:MeshConnectivity', ...
    'The two routes generated different P3 connectivity.');

%% Boundary-condition consistency
boundaryNodesMode3 = ...
    equilibriumMode3.mesh.boundaryNodes;

boundaryErrorMode3 = norm( ...
    equilibriumMode3.psi(boundaryNodesMode3) ...
    - psiBoundary, inf);

assert(boundaryErrorMode3 < tolerance.boundary, ...
    'TEST_PQ_ROUTE:Mode3Boundary', ...
    'The mode-3 boundary condition is not satisfied.');

%% q-constraint error on directly evaluated surfaces
qCalculated = ...
    equilibriumMode3.qResult.q(:);

qPrescribed = ...
    equilibriumMode3.profile.qPrescribed.q(:);

qGeometryFactor = ...
    equilibriumMode3.qGeometry.qPerF(:);

assert(numel(qCalculated) == numel(qPrescribed) && ...
       numel(qCalculated) == numel(qGeometryFactor), ...
    'TEST_PQ_ROUTE:QEvaluationSize', ...
    'The calculated, prescribed, and geometry q arrays are inconsistent.');

% Exclude the separatrix value because qPerF(psiN=1) is not evaluated
% directly. Boundary q is obtained through extrapolation.
validQConstraint = ...
    isfinite(qCalculated) & ...
    isfinite(qPrescribed) & ...
    isfinite(qGeometryFactor) & ...
    qPrescribed ~= 0;

assert(nnz(validQConstraint) >= 3, ...
    'TEST_PQ_ROUTE:TooFewQPoints', ...
    'Too few valid q surfaces are available for comparison.');

qConstraintRelativeError = ...
    (qCalculated(validQConstraint) ...
     - qPrescribed(validQConstraint)) ...
    ./ qPrescribed(validQConstraint);

qConstraintLogError = ...
    log(abs( ...
        qCalculated(validQConstraint) ...
        ./ qPrescribed(validQConstraint)));

qConstraintMaximum = ...
    max(abs(qConstraintRelativeError));

qConstraintRmsLog = ...
    sqrt(mean(qConstraintLogError.^2));

assert(qConstraintMaximum <= ...
        tolerance.qConstraintMax*(1+1.0e-10), ...
    'TEST_PQ_ROUTE:QConstraintMaximum', ...
    ['Maximum relative q constraint error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    qConstraintMaximum, tolerance.qConstraintMax);

assert(qConstraintRmsLog <= ...
        tolerance.qConstraintRmsLog*(1+1.0e-10), ...
    'TEST_PQ_ROUTE:QConstraintRms', ...
    ['RMS log-q constraint error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    qConstraintRmsLog, tolerance.qConstraintRmsLog);

% Verify that the finalized output and outer-solver diagnostics describe
% the same final q state.
reportedQMaximum = ...
    equilibriumMode3.constraintResult.finalMaxAbsRelativeQ;

reportedQRmsLog = ...
    equilibriumMode3.constraintResult.finalRmsLogQ;

metricTolerance = 1.0e-12;

assert(abs(qConstraintMaximum-reportedQMaximum) ...
        <= metricTolerance*max(1, abs(reportedQMaximum)), ...
    'TEST_PQ_ROUTE:QMaximumDiagnostic', ...
    ['The finalized q profile and constraintResult report ', ...
     'different maximum q errors.']);

assert(abs(qConstraintRmsLog-reportedQRmsLog) ...
        <= metricTolerance*max(1, abs(reportedQRmsLog)), ...
    'TEST_PQ_ROUTE:QRmsDiagnostic', ...
    ['The finalized q profile and constraintResult report ', ...
     'different RMS q errors.']);

%% Route-to-route q comparison
%
% Compare only directly integrated contour surfaces. The axis value uses a
% Hessian reconstruction and the boundary value uses extrapolation, so they
% are tested through the p-q convergence metrics above.

commonPsiN = ...
    equilibriumMode1.profile.psiN(:);

qMode1 = ...
    equilibriumMode1.profile.q(:);

qMode3 = ...
    equilibriumMode3.profile.q(:);

contourRegion = ...
    commonPsiN >= 0.05 & ...
    commonPsiN <= 0.95;

qRouteRelativeError = ...
    (qMode3(contourRegion)-qMode1(contourRegion)) ...
    ./ qMode1(contourRegion);

qRouteRms = ...
    sqrt(mean(qRouteRelativeError.^2));

qRouteMaximum = ...
    max(abs(qRouteRelativeError));

assert(qRouteRms < tolerance.qContourRms, ...
    'TEST_PQ_ROUTE:QRouteRms', ...
    ['Route-to-route q RMS error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    qRouteRms, tolerance.qContourRms);

assert(qRouteMaximum < tolerance.qContourMax, ...
    'TEST_PQ_ROUTE:QRouteMaximum', ...
    ['Route-to-route q maximum error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    qRouteMaximum, tolerance.qContourMax);

%% Poloidal-flux consistency
psiRelativeL2 = relative_l2_error( ...
    equilibriumMode3.psi, ...
    equilibriumMode1.psi);

psiNDifference = ...
    equilibriumMode3.psiN ...
    - equilibriumMode1.psiN;

psiNRootMeanSquare = ...
    sqrt(mean(psiNDifference.^2));

assert(psiRelativeL2 < tolerance.psiRelativeL2, ...
    'TEST_PQ_ROUTE:PsiRelativeL2', ...
    ['Route-to-route psi relative L2 error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    psiRelativeL2, tolerance.psiRelativeL2);

assert(psiNRootMeanSquare < ...
        tolerance.psiNRootMeanSquare, ...
    'TEST_PQ_ROUTE:PsiNRms', ...
    ['Route-to-route psiN RMS error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    psiNRootMeanSquare, ...
    tolerance.psiNRootMeanSquare);

%% F, G, and FFprime consistency
FRelativeL2 = relative_l2_error( ...
    equilibriumMode3.profile.Fpol, ...
    equilibriumMode1.profile.Fpol);

GRelativeL2 = relative_l2_error( ...
    equilibriumMode3.profile.Gpol, ...
    equilibriumMode1.profile.Gpol);

FFprimeRelativeL2 = relative_l2_error( ...
    equilibriumMode3.profile.FdF_dpsiN, ...
    equilibriumMode1.profile.FdF_dpsiN);

assert(FRelativeL2 < tolerance.FRelativeL2, ...
    'TEST_PQ_ROUTE:FRelativeL2', ...
    ['Route-to-route F relative L2 error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    FRelativeL2, tolerance.FRelativeL2);

assert(GRelativeL2 < tolerance.GRelativeL2, ...
    'TEST_PQ_ROUTE:GRelativeL2', ...
    ['Route-to-route G relative L2 error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    GRelativeL2, tolerance.GRelativeL2);

% FFprime is represented directly, but remains the most sensitive profile
% in the inverse route and therefore retains a looser route tolerance.
assert(FFprimeRelativeL2 < ...
        tolerance.FFprimeRelativeL2, ...
    'TEST_PQ_ROUTE:FFprimeRelativeL2', ...
    ['Route-to-route FFprime relative L2 error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    FFprimeRelativeL2, ...
    tolerance.FFprimeRelativeL2);

%% Pressure consistency
pressureDifference = ...
    equilibriumMode3.profile.pressure ...
    - equilibriumMode1.profile.pressure;

pressureScale = max( ...
    norm(equilibriumMode1.profile.pressure, inf), ...
    1);

pressureRelativeInfinity = ...
    norm(pressureDifference, inf)/pressureScale;

assert(pressureRelativeInfinity < ...
        tolerance.pressureRelativeInfinity, ...
    'TEST_PQ_ROUTE:PressureConsistency', ...
    ['The two routes reconstructed different pressure profiles: ', ...
     'relative infinity error %.3e.'], ...
    pressureRelativeInfinity);

%% Magnetic-axis consistency
axisPositionError = norm( ...
    equilibriumMode3.axisPoint ...
    - equilibriumMode1.axisPoint);

axisFluxRelativeError = relative_scalar_error( ...
    equilibriumMode3.global.simag, ...
    equilibriumMode1.global.simag);

assert(axisPositionError < tolerance.axisPosition, ...
    'TEST_PQ_ROUTE:AxisPosition', ...
    ['Route-to-route axis-position error %.3e m exceeds ', ...
     'the tolerance %.3e m.'], ...
    axisPositionError, tolerance.axisPosition);

assert(axisFluxRelativeError < ...
        tolerance.axisFluxRelative, ...
    'TEST_PQ_ROUTE:AxisFlux', ...
    ['Route-to-route relative axis-flux error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    axisFluxRelativeError, ...
    tolerance.axisFluxRelative);

%% Global-parameter consistency
IpRelativeError = relative_scalar_error( ...
    equilibriumMode3.global.Ip, ...
    equilibriumMode1.global.Ip);

volumeRelativeError = relative_scalar_error( ...
    equilibriumMode3.global.volume, ...
    equilibriumMode1.global.volume);

assert(IpRelativeError < tolerance.IpRelative, ...
    'TEST_PQ_ROUTE:PlasmaCurrent', ...
    ['Route-to-route plasma-current error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    IpRelativeError, tolerance.IpRelative);

% Volume depends on the fixed mesh and boundary, not on the profile route.
% It should therefore agree to roundoff.
assert(volumeRelativeError < tolerance.volumeRelative, ...
    'TEST_PQ_ROUTE:Volume', ...
    ['Route-to-route volume error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    volumeRelativeError, tolerance.volumeRelative);

%% Visual route comparison
routeComparison = plot_pq_route_comparison( ...
    equilibriumMode1, equilibriumMode3);

assert(isgraphics(routeComparison.figure,'figure'), ...
    'TEST_PQ_ROUTE:ComparisonFigure', ...
    'The mode-1/mode-3 comparison figure was not created.');

comparisonMetricVector = [ ...
    routeComparison.metrics.psiNRootMeanSquare; ...
    routeComparison.metrics.psiNMaximum; ...
    routeComparison.metrics.qRelativeRootMeanSquare; ...
    routeComparison.metrics.qRelativeMaximum; ...
    routeComparison.metrics.FRelativeL2; ...
    routeComparison.metrics.FFprimeRelativeL2];

assert(all(isfinite(comparisonMetricVector)), ...
    'TEST_PQ_ROUTE:ComparisonMetrics', ...
    'The visual route comparison returned a non-finite metric.');

%% Report
fprintf('\n');
fprintf('p-q route-consistency integration test passed.\n');
fprintf('\n');

fprintf('  Mode-1 Picard iterations       = %d\n', ...
    equilibriumMode1.solverResult.iterations);

fprintf('  Mode-3 outer iterations        = %d\n', ...
    equilibriumMode3.constraintResult.outerIterations);

fprintf('  Final mode-3 inner iterations  = %d\n', ...
    equilibriumMode3.solverResult.iterations);

fprintf('  Mode-3 full-GS evaluations     = %d\n', ...
    equilibriumMode3.constraintResult.functionEvaluations);

fprintf('  Reference FFprime coefficients = %s\n', ...
    mat2str(referenceFFprimeCoefficients.',6));

fprintf('  Final FFprime coefficients     = %s\n', ...
    mat2str(equilibriumMode3.FFprimeModel.coefficients.',6));

fprintf('  Reference/recovered curvature  = %.3e / %.3e\n', ...
    referenceCurvedFraction,recoveredCurvedFraction);

fprintf('  Reduced-basis projection floor = %.3e\n', ...
    referenceBasisError);

fprintf('\n');

fprintf('  q constraint max relative      = %.3e\n', ...
    qConstraintMaximum);

fprintf('  q constraint RMS log           = %.3e\n', ...
    qConstraintRmsLog);

fprintf('  q route RMS / max              = %.3e / %.3e\n', ...
    qRouteRms, qRouteMaximum);

fprintf('\n');

fprintf('  psi relative L2                = %.3e\n', ...
    psiRelativeL2);

fprintf('  psiN RMS                       = %.3e\n', ...
    psiNRootMeanSquare);

fprintf('  F relative L2                  = %.3e\n', ...
    FRelativeL2);

fprintf('  G relative L2                  = %.3e\n', ...
    GRelativeL2);

fprintf('  FFprime relative L2            = %.3e\n', ...
    FFprimeRelativeL2);

fprintf('\n');

fprintf('  axis-position error [m]        = %.3e\n', ...
    axisPositionError);

fprintf('  relative axis-flux error       = %.3e\n', ...
    axisFluxRelativeError);

fprintf('  relative Ip error              = %.3e\n', ...
    IpRelativeError);

fprintf('  relative volume error          = %.3e\n', ...
    volumeRelativeError);

fprintf('\n');

fprintf('  comparison figure              = figure %d\n', ...
    routeComparison.figure.Number);

fprintf('  mode-1/mode-3 boundary errors  = %.3e / %.3e\n', ...
    boundaryErrorMode1, boundaryErrorMode3);


%% Local utility functions

function value = relative_l2_error(candidate, reference)
%RELATIVE_L2_ERROR Relative Euclidean error.

    candidate = candidate(:);
    reference = reference(:);

    if numel(candidate) ~= numel(reference)
        error('TEST_PQ_ROUTE:ComparisonSize', ...
            'The compared vectors must have equal lengths.');
    end

    numerator = norm(candidate-reference);
    denominator = max(norm(reference), eps);

    value = numerator/denominator;
end


function value = relative_scalar_error(candidate, reference)
%RELATIVE_SCALAR_ERROR Relative scalar error.

    validateattributes(candidate, {'numeric'}, ...
        {'real', 'finite', 'scalar'});

    validateattributes(reference, {'numeric'}, ...
        {'real', 'finite', 'scalar'});

    value = ...
        abs(candidate-reference)/max(abs(reference), eps);
end
