%% test_qsolve.m
% End-to-end test of the prescribed-pprime, prescribed-q GS route.
%
% This test starts directly from p'(psi_N) and q(psi_N). It does not
% construct a mode-1 pprime-FFprime reference equilibrium first.
%
% Solver convention:
%
%   psiN = 0 at the magnetic axis
%   psiN = 1 at the fixed boundary
%
%   pprime is dp/dpsiN.

clearvars;
close all;
clc;

%% Repository setup
thisDirectory = fileparts(mfilename('fullpath'));

rootDirectory = fullfile(thisDirectory, '..', '..');

addpath(rootDirectory);
setup_solve_GS;

%% Test tolerances
tolerance = struct();
tolerance.boundary = 1.0e-13;
tolerance.qConstraintMax = 2.0e-3;
tolerance.qConstraintRmsLog = 1.0e-3;
tolerance.metricConsistency = 1.0e-12;
tolerance.profileConsistency = 1.0e-13;
tolerance.FboundaryRelative = 1.0e-12;

%% Miller boundary and numerical resolution
R0 = 3.0;
aMinor = 0.8;
kappa = 1.5;
delta = 0.4;

B0 = 3.0;
pedge = 0.0;
psiBoundary = 0.0;

nBoundary = 100;
NR = 128;
NZ = 48;
coarseNR = 64;
coarseNZ = 32;
nProfile = 101;
quadratureDegree = 7;

theta = (0:nBoundary-1).'*(2*pi/nBoundary);
triangularityAngle = asin(delta);

RBoundary = R0 + aMinor*cos( ...
    theta + triangularityAngle*sin(theta));
ZBoundary = kappa*aMinor*sin(theta);

if any(RBoundary <= 0)
    error('TEST_QSOLVE:InvalidBoundary', ...
        'The Miller boundary contains R <= 0.');
end

%% Prescribed pprime and q profiles
psiNProfile = linspace(0,1,nProfile).';

% Pressure derivative:
%
%   pprime(psiN) = pprime0*(1-psiN^aP)^bP
pprime0 = -1.0e6;
aP = 1.5;
bP = 2.0;

pprime = pprime0*(1-psiNProfile.^aP).^bP;

% Cubic q profile satisfying
%
%   q(0)  = q0
%   q'(0) = shear0
%   q(1)  = qedge
%   q'(1) = shear1
q0 = 1.03;
qedge = 4.2;
shear0 = 0.84375;
shear1 = 9.0;

q1 = shear0;
q23 = [1,1; 2,3] \ [ ...
    qedge-q0-q1; ...
    shear1-q1];

q2 = q23(1);
q3 = q23(2);

q = q0 ...
    + q1*psiNProfile ...
    + q2*psiNProfile.^2 ...
    + q3*psiNProfile.^3;

if any(~isfinite(pprime)) || any(~isfinite(q)) || any(q <= 0)
    error('TEST_QSOLVE:InvalidProfiles', ...
        'The prescribed pprime and q profiles must be finite and q > 0.');
end

profileScale = max(1,max(abs(q)));

if abs(q(1)-q0) > 100*eps(profileScale) || ...
        abs(q(end)-qedge) > 100*eps(profileScale)
    error('TEST_QSOLVE:QEndpointConstruction', ...
        'The cubic q profile does not satisfy its endpoint constraints.');
end

qTarget = struct( ...
    'psiN',psiNProfile, ...
    'q',q);

%% Prescribed-pprime, prescribed-q solve input
input = struct();

input.grid = struct( ...
    'nBoundary',nBoundary, ...
    'NR',NR, ...
    'NZ',NZ, ...
    'quadratureDegree',quadratureDegree, ...
    'nProfile',nProfile);

input.dim = struct( ...
    'R0',R0, ...
    'B0',B0, ...
    'aMinor',aMinor);

input.boundary = struct( ...
    'R',RBoundary, ...
    'Z',ZBoundary, ...
    'psiBoundary',psiBoundary);

input.Picard = struct( ...
    'omega',0.5, ...
    'maxIterations',120, ...
    'updateTolerance',1.0e-9, ...
    'residualTolerance',1.0e-9, ...
    'axisMode','max', ...
    'symmetryTolerance',1.0e-12, ...
    'fluxSpanTolerance',1.0e-12);

input.profile = struct();
input.profile.mode = 3;
input.profile.pprime = pprime;
input.profile.q = qTarget;
input.profile.pedge = pedge;

% The p-q problem needs one F normalization. Fix the boundary value to
% the vacuum value and construct the first FFprime estimate cylindrically.
Fboundary = R0*B0;

input.profile.normalization = struct( ...
    'mode','fixed_Fb', ...
    'Fb',Fboundary);

input.profile.FSign = sign(Fboundary);
input.profile.initial = struct('type','cylindrical');

input.pqConstraint = struct();

input.pqConstraint.outer = struct( ...
    'maxIterations',30, ...
    'qRelativeTolerance',tolerance.qConstraintMax, ...
    'qRmsLogTolerance',tolerance.qConstraintRmsLog, ...
    'minimumIterations',2, ...
    'minimumQPoints',3, ...
    'stopOnInnerNonconvergence',true, ...
    'errorOnFailure',false, ...
    'storePsiHistory',false, ...
    'verbose',false);

% Eight low-order modes resolve the q-profile shape on this mesh while
% retaining a compact reduced inverse problem. A very small penalty only
% regularizes nearly singular coefficient directions.
input.pqConstraint.FFprime = struct( ...
    'nBasis',8, ...
    'enforceZeroEdge',false, ...
    'regularization',1.0e-10, ...
    'jacobianRidge',1.0e-12, ...
    'initialDamping',1.0e-3, ...
    'maxCoefficientStep',5.0, ...
    'fitRange',[0,0.95], ...
    'axisWeight',1.0);

input.output = struct( ...
    'verbose',true, ...
    'checkTime',true, ...
    'showPlot',true);

%% Solve directly from pprime and q on two mesh levels
% First determine a mesh-independent FFprime profile on a cheaper grid.
% Only that profile is transferred; psi DOFs are not shared between the
% two unrelated meshes. The fine solve therefore remains a complete GS
% solve, but starts close to the correct p-q branch.
multilevelTimer = tic;

coarseInput = input;
coarseInput.grid.NR = coarseNR;
coarseInput.grid.NZ = coarseNZ;
coarseInput.output.verbose = false;
coarseInput.output.checkTime = false;
coarseInput.output.showPlot = false;

coarseEquilibrium = solve_GS(coarseInput);

assert(coarseEquilibrium.constraintResult.converged, ...
    'TEST_QSOLVE:CoarseOuterConvergence', ...
    ['The coarse p-q initialization did not converge. ', ...
     'Termination reason: %s.'], ...
    coarseEquilibrium.constraintResult.terminationReason);

input.profile.initial = struct( ...
    'type','FFprime', ...
    'psiN',coarseEquilibrium.profile.psiN, ...
    'FFprime',coarseEquilibrium.profile.FdF_dpsiN);

equilibrium = solve_GS(input);
multilevelElapsed = toc(multilevelTimer);

%% Output-contract and convergence checks
assert(isfield(equilibrium,'constraintResult'), ...
    'TEST_QSOLVE:MissingConstraintResult', ...
    'Mode 3 did not return equilibrium.constraintResult.');

assert(isfield(equilibrium,'FFprimeModel'), ...
    'TEST_QSOLVE:MissingFFprimeModel', ...
    'Mode 3 did not return equilibrium.FFprimeModel.');

assert(isfield(equilibrium.profile,'qPrescribed'), ...
    'TEST_QSOLVE:MissingPrescribedQ', ...
    'Mode 3 did not return equilibrium.profile.qPrescribed.');

assert(equilibrium.profile.mode == 3, ...
    'TEST_QSOLVE:OutputMode', ...
    'The finalized equilibrium did not preserve profile mode 3.');

assert(equilibrium.solverResult.converged, ...
    'TEST_QSOLVE:InnerConvergence', ...
    'The final inner Picard solve did not converge.');

assert(equilibrium.constraintResult.converged, ...
    'TEST_QSOLVE:OuterConvergence', ...
    ['The p-q outer iteration did not converge. ', ...
     'Termination reason: %s.'], ...
    equilibrium.constraintResult.terminationReason);

assert(equilibrium.solverResult.finalRelativeResidual ...
        < input.Picard.residualTolerance, ...
    'TEST_QSOLVE:InnerResidual', ...
    'The final inner weak residual exceeds its tolerance.');

assert(equilibrium.constraintResult.outerIterations >= ...
        input.pqConstraint.outer.minimumIterations, ...
    'TEST_QSOLVE:OuterIterationNotExercised', ...
    'The solve did not exercise the requested outer iterations.');

coefficientStepHistory = ...
    equilibrium.constraintResult.history.coefficientStep;
finiteCoefficientStep = ...
    coefficientStepHistory(isfinite(coefficientStepHistory));

assert(~isempty(finiteCoefficientStep) && ...
       any(finiteCoefficientStep > 100*eps), ...
    'TEST_QSOLVE:ZeroFFprimeUpdate', ...
    'The p-q solve did not apply a nonzero FFprime update.');

%% Boundary and profile checks
boundaryNodes = equilibrium.mesh.boundaryNodes;
boundaryError = norm( ...
    equilibrium.psi(boundaryNodes)-psiBoundary,inf);

assert(boundaryError < tolerance.boundary, ...
    'TEST_QSOLVE:Boundary', ...
    'The fixed-boundary condition is not satisfied.');

pprimeDifference = norm( ...
    equilibrium.profile.dp_dpsiN(:)-pprime,inf);
pprimeScale = max(1,norm(pprime,inf));

assert(pprimeDifference <= ...
        tolerance.profileConsistency*pprimeScale, ...
    'TEST_QSOLVE:PprimeProfile', ...
    'The finalized equilibrium did not preserve the prescribed pprime.');

assert(all(isfinite(equilibrium.profile.FdF_dpsiN)) && ...
       all(isfinite(equilibrium.profile.Fpol)) && ...
       all(isfinite(equilibrium.profile.Gpol)) && ...
       all(equilibrium.profile.Gpol > 0), ...
    'TEST_QSOLVE:InvalidFProfile', ...
    'The reconstructed FFprime, F, or G profile is invalid.');

FboundaryError = abs( ...
    equilibrium.profile.Fpol(end)-Fboundary) ...
    /max(abs(Fboundary),eps);

assert(FboundaryError < tolerance.FboundaryRelative, ...
    'TEST_QSOLVE:FBoundary', ...
    'The reconstructed F profile violates the fixed-Fb normalization.');

%% q-constraint checks on the directly evaluated surfaces
qCalculated = equilibrium.qResult.q(:);
qPrescribed = equilibrium.profile.qPrescribed.q(:);
qGeometryFactor = equilibrium.qGeometry.qPerF(:);

assert(numel(qCalculated) == numel(qPrescribed) && ...
       numel(qCalculated) == numel(qGeometryFactor), ...
    'TEST_QSOLVE:QEvaluationSize', ...
    'The calculated, prescribed, and geometry q arrays are inconsistent.');

validQConstraint = ...
    isfinite(qCalculated) & ...
    isfinite(qPrescribed) & ...
    isfinite(qGeometryFactor) & ...
    qPrescribed ~= 0;

assert(nnz(validQConstraint) >= 3, ...
    'TEST_QSOLVE:TooFewQPoints', ...
    'Too few valid q surfaces are available for comparison.');

qConstraintRelativeError = ...
    (qCalculated(validQConstraint)-qPrescribed(validQConstraint)) ...
    ./ qPrescribed(validQConstraint);

qConstraintLogError = log(abs( ...
    qCalculated(validQConstraint) ...
    ./ qPrescribed(validQConstraint)));

qConstraintMaximum = max(abs(qConstraintRelativeError));
qConstraintRmsLog = sqrt(mean(qConstraintLogError.^2));

assert(qConstraintMaximum <= ...
        tolerance.qConstraintMax*(1+1.0e-10), ...
    'TEST_QSOLVE:QConstraintMaximum', ...
    ['Maximum relative q constraint error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    qConstraintMaximum,tolerance.qConstraintMax);

assert(qConstraintRmsLog <= ...
        tolerance.qConstraintRmsLog*(1+1.0e-10), ...
    'TEST_QSOLVE:QConstraintRms', ...
    ['RMS log-q constraint error %.3e exceeds ', ...
     'the tolerance %.3e.'], ...
    qConstraintRmsLog,tolerance.qConstraintRmsLog);

reportedQMaximum = ...
    equilibrium.constraintResult.finalMaxAbsRelativeQ;
reportedQRmsLog = ...
    equilibrium.constraintResult.finalRmsLogQ;

assert(abs(qConstraintMaximum-reportedQMaximum) <= ...
        tolerance.metricConsistency*max(1,abs(reportedQMaximum)), ...
    'TEST_QSOLVE:QMaximumDiagnostic', ...
    ['The finalized q profile and constraintResult report ', ...
     'different maximum q errors.']);

assert(abs(qConstraintRmsLog-reportedQRmsLog) <= ...
        tolerance.metricConsistency*max(1,abs(reportedQRmsLog)), ...
    'TEST_QSOLVE:QRmsDiagnostic', ...
    ['The finalized q profile and constraintResult report ', ...
     'different RMS q errors.']);

%% Report
fprintf('\n');
fprintf('Prescribed-pprime, prescribed-q integration test passed.\n');
fprintf('\n');
fprintf('  Coarse-grid outer iterations = %d\n', ...
    coarseEquilibrium.constraintResult.outerIterations);
fprintf('  Coarse-grid GS evaluations   = %d\n', ...
    coarseEquilibrium.constraintResult.functionEvaluations);
fprintf('  Fine-grid outer iterations   = %d\n', ...
    equilibrium.constraintResult.outerIterations);
fprintf('  Fine-grid GS evaluations     = %d\n', ...
    equilibrium.constraintResult.functionEvaluations);
fprintf('  Two-level elapsed time       = %.3f s\n', ...
    multilevelElapsed);
fprintf('  Final inner iterations       = %d\n', ...
    equilibrium.solverResult.iterations);
fprintf('  Final inner weak residual    = %.3e\n', ...
    equilibrium.solverResult.finalRelativeResidual);
fprintf('  q constraint max relative    = %.3e\n', ...
    qConstraintMaximum);
fprintf('  q constraint RMS log         = %.3e\n', ...
    qConstraintRmsLog);
fprintf('  Boundary error               = %.3e\n', ...
    boundaryError);
fprintf('  Fixed-Fb relative error      = %.3e\n', ...
    FboundaryError);
fprintf('  Final FFprime coefficients   = %s\n', ...
    mat2str(equilibrium.FFprimeModel.coefficients.',6));
