%% test_qsolve_indented_fixed_q.m
% Direct prescribed-pprime, prescribed-q solve using the profiles and
% physical normalization of test_qsolve.m, with only the fixed-boundary
% shape replaced by an indented C-shape.

clearvars;
close all;
clc;

%% Repository setup
thisDirectory = fileparts(mfilename('fullpath'));
rootDirectory = fullfile(thisDirectory, '..', '..');

addpath(rootDirectory);
setup_solve_GS;

%% Tolerances copied from test_qsolve.m
tolerance = struct();
tolerance.boundary = 1.0e-13;
tolerance.qConstraintMax = 2.0e-3;
tolerance.qConstraintRmsLog = 1.0e-3;
tolerance.profileConsistency = 1.0e-13;
tolerance.FboundaryRelative = 1.0e-12;

%% Physical parameters from test_qsolve.m and indented shape controls
R0 = 3.0;
aMinor = 0.8;
B0 = 3.0;

% C-shape boundary parameters. These are intentionally grouped here so
% stronger elongation or indentation can be tested without changing the
% prescribed profiles below.
kappa = 3.0;
delta = -0.4;
indent = 0.8;

pedge = 0.0;
psiBoundary = 0.0;

nBoundary = 100;
NR = 96;
NZ = 96;
coarseNR = 48;
coarseNZ = 64;
nProfile = 101;
quadratureDegree = 7;

qInteriorPsiN = [0.05:0.10:0.85, 0.90, 0.95].';
coarseContourNR = 80;
fineContourNR = 120;

showPlot = true;

%% Indented C-shape boundary
theta = (0:nBoundary-1).'*(2*pi/nBoundary);
triangularityAngle = asin(delta);

RBoundary = R0 + aMinor*cos( ...
    theta+triangularityAngle*sin(theta)) ...
    -indent*aMinor*(0.5+0.5*cos(theta)).^3;
ZBoundary = kappa*aMinor*sin(theta);

assert(all(RBoundary > 0), ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:InvalidBoundary', ...
    'The indented boundary contains R <= 0.');

%% Prescribed pprime and q copied from test_qsolve.m
psiNProfile = linspace(0, 1, nProfile).';

pprime0 = -1.0e6;
aP = 1.5;
bP = 2.0;
pprime = pprime0*(1-psiNProfile.^aP).^bP;

q0 = 1.03;
qedge = 4.2;
shear0 = 0.84375;
shear1 = 9.0;

q1 = shear0;
q23 = [1, 1; 2, 3]\[qedge-q0-q1; shear1-q1];
q2 = q23(1);
q3 = q23(2);

q = q0 + q1*psiNProfile ...
    +q2*psiNProfile.^2 + q3*psiNProfile.^3;
qTarget = struct('psiN', psiNProfile, 'q', q);

assert(all(isfinite(pprime)) && all(isfinite(q)) && all(q > 0), ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:InvalidProfiles', ...
    'The prescribed pprime and q profiles must be finite and q > 0.');

%% Common mode-3 input
input = struct();
input.grid = struct( ...
    'nBoundary', nBoundary, ...
    'NR', NR, ...
    'NZ', NZ, ...
    'quadratureDegree', quadratureDegree, ...
    'nProfile', nProfile);
input.dim = struct( ...
    'R0', R0, ...
    'B0', B0, ...
    'aMinor', aMinor);
input.boundary = struct( ...
    'R', RBoundary, ...
    'Z', ZBoundary, ...
    'psiBoundary', psiBoundary);
input.Picard = struct( ...
    'omega', 0.5, ...
    'maxIterations', 250, ...
    'updateTolerance', 2.0e-7, ...
    'residualTolerance', 5.0e-7, ...
    'axisMode', 'max', ...
    'symmetryTolerance', 1.0e-12, ...
    'fluxSpanTolerance', 1.0e-12);

Fboundary = R0*B0;

input.profile = struct();
input.profile.mode = 3;
input.profile.pprime = pprime;
input.profile.q = qTarget;
input.profile.pedge = pedge;
input.profile.normalization = struct( ...
    'mode', 'fixed_Fb', ...
    'Fb', Fboundary);
input.profile.FSign = sign(Fboundary);
input.profile.initial = struct('type', 'cylindrical');

input.pqConstraint = struct();
input.pqConstraint.outer = struct( ...
    'maxIterations', 30, ...
    'qRelativeTolerance', tolerance.qConstraintMax, ...
    'qRmsLogTolerance', tolerance.qConstraintRmsLog, ...
    'minimumIterations', 2, ...
    'minimumQPoints', 3, ...
    'errorOnFailure', false, ...
    'verbose', false);
input.pqConstraint.FFprime = struct( ...
    'nBasis', 8, ...
    'enforceZeroEdge', false, ...
    'regularization', 1.0e-10, ...
    'jacobianRidge', 1.0e-12, ...
    'initialDamping', 1.0e-3, ...
    'maxCoefficientStep', 5.0, ...
    'initialScales', [1, 0.5, 0], ...
    'fitRange', [0, 0.95], ...
    'axisWeight', 1.0);
input.qEvaluation = struct( ...
    'interiorPsiN', qInteriorPsiN, ...
    'contourNR', fineContourNR);
input.output = struct( ...
    'verbose', false, ...
    'checkTime', false, ...
    'showPlot', showPlot);

%% Coarse-to-fine direct p-q solve
% Only the converged FFprime profile is transferred. The fine-grid flux is
% solved from its own distance-to-boundary initial condition.
totalTimer = tic;

coarseInput = input;
coarseInput.grid.NR = coarseNR;
coarseInput.grid.NZ = coarseNZ;
coarseInput.qEvaluation.contourNR = coarseContourNR;
coarseInput.output.showPlot = false;

coarseEquilibrium = solve_GS(coarseInput);

assert(coarseEquilibrium.constraintResult.converged, ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:CoarseConvergence', ...
    ['The coarse indented p-q solve did not converge. ', ...
     'Termination reason: %s.'], ...
    coarseEquilibrium.constraintResult.terminationReason);

input.profile.initial = struct( ...
    'type', 'FFprime', ...
    'psiN', coarseEquilibrium.profile.psiN, ...
    'FFprime', coarseEquilibrium.profile.FdF_dpsiN);
input.pqConstraint.FFprime.initialScales = 1.0;

equilibrium = solve_GS(input);
totalElapsed = toc(totalTimer);

%% Final validation
assert(equilibrium.solverResult.converged, ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:InnerConvergence', ...
    'The final inner GS solve did not converge.');
assert(equilibrium.constraintResult.converged, ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:OuterConvergence', ...
    'The final p-q solve failed: %s.', ...
    equilibrium.constraintResult.terminationReason);

[qMaximum, qRmsLog] = calculate_q_error(equilibrium, 0.95);
boundaryError = norm( ...
    equilibrium.psi(equilibrium.mesh.boundaryNodes)-psiBoundary, inf);
FboundaryError = abs(equilibrium.profile.Fpol(end)-Fboundary) ...
    /max(abs(Fboundary), eps);
pprimeError = norm(equilibrium.profile.dp_dpsiN-pprime, inf) ...
    /max(1, norm(pprime, inf));

assert(qMaximum <= tolerance.qConstraintMax*(1+1.0e-10), ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:QMaximum', ...
    'Maximum relative q error %.3e exceeds %.3e.', ...
    qMaximum, tolerance.qConstraintMax);
assert(qRmsLog <= tolerance.qConstraintRmsLog*(1+1.0e-10), ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:QRms', ...
    'RMS log-q error %.3e exceeds %.3e.', ...
    qRmsLog, tolerance.qConstraintRmsLog);
assert(boundaryError < tolerance.boundary, ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:Boundary', ...
    'The fixed-boundary condition is not satisfied.');
assert(FboundaryError < tolerance.FboundaryRelative, ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:FBoundary', ...
    'The fixed-Fb normalization is not satisfied.');
assert(pprimeError <= tolerance.profileConsistency, ...
    'TEST_QSOLVE_INDENTED_FIXED_Q:Pprime', ...
    'The prescribed pprime profile changed during the solve.');

fprintf('\nIndented C-shape fixed-q test passed.\n');
fprintf('  kappa / indentation          = %.1f / %.1f\n', ...
    kappa, indent);
fprintf('  Coarse outer / evaluations   = %d / %d\n', ...
    coarseEquilibrium.constraintResult.outerIterations, ...
    coarseEquilibrium.constraintResult.functionEvaluations);
fprintf('  Fine outer / evaluations     = %d / %d\n', ...
    equilibrium.constraintResult.outerIterations, ...
    equilibrium.constraintResult.functionEvaluations);
fprintf('  Total elapsed time           = %.1f s\n', totalElapsed);
fprintf('  Final inner weak residual    = %.3e\n', ...
    equilibrium.solverResult.finalRelativeResidual);
fprintf('  q constraint max relative    = %.3e\n', qMaximum);
fprintf('  q constraint RMS log         = %.3e\n', qRmsLog);
fprintf('  Boundary error               = %.3e\n', boundaryError);


function [maximumRelative, rmsLog] = ...
    calculate_q_error(equilibrium, fitMaximum)
%CALCULATE_Q_ERROR Recompute the outer q-convergence metrics.

    psiN = equilibrium.qGeometry.psiN(:);
    qCalculated = equilibrium.qResult.q(:);
    qTarget = equilibrium.profile.qPrescribed.q(:);
    qPerF = equilibrium.qGeometry.qPerF(:);

    valid = isfinite(psiN) & isfinite(qCalculated) ...
        &isfinite(qTarget) & isfinite(qPerF) ...
        &qTarget ~= 0 & psiN <= fitMaximum;
    relativeError = ...
        (qCalculated(valid)-qTarget(valid))./qTarget(valid);
    logError = log(abs(qCalculated(valid)./qTarget(valid)));

    maximumRelative = max(abs(relativeError));
    rmsLog = sqrt(mean(logError.^2));
end
