%% test_qsolve_indented.m
% Validate the prescribed-pprime, prescribed-q route on indented C-shapes.
%
% The sweep covers
%
%   elongation  = 3, 4, 5
%   indentation = 0.2, 0.5, 0.8
%
% For each shape, a mode-1 reference equilibrium generates a realizable
% target q.  A separate mode-3 solve then starts from 90% of the reference
% FFprime and must recover the target q.  This round trip verifies the
% inverse route against a known solution while exercising a nonzero update.

clearvars;
close all;
clc;

%% Repository setup
thisDirectory = fileparts(mfilename('fullpath'));
rootDirectory = fullfile(thisDirectory, '..', '..');

addpath(rootDirectory);
setup_solve_GS;

%% Shape sweep and numerical resolution
elongations = [3.0, 4.0, 5.0];
indentations = [0.2, 0.5, 0.8];

R0 = 3.0;
aMinor = 1.0;
delta = -0.4;
B0 = 2.0;
pedge = 0.0;
psiBoundary = 0.0;

nBoundary = 100;
NR = 48;
NZ = 64;
nProfile = 101;
quadratureDegree = 7;

qInteriorPsiN = [0.05:0.10:0.85, 0.90, 0.95].';
qContourNR = 100;

showPlot = true;

%% Accuracy requirements
tolerance = struct();
tolerance.boundary = 1.0e-13;
tolerance.qConstraintMax = 1.0e-3;
tolerance.qConstraintRmsLog = 5.0e-4;
tolerance.FboundaryRelative = 1.0e-12;
tolerance.profileConsistency = 1.0e-13;

%% Common prescribed profiles
psiNProfile = linspace(0, 1, nProfile).';

pprime0 = -1.0e6;
aP = 1.5;
bP = 2.0;
pprime = pprime0*(1-psiNProfile.^aP).^bP;

Fboundary = R0*B0;

referenceFFprime = 0.6*(1-psiNProfile.^2);
initialFFprime = 0.9*referenceFFprime;

%% Enumerate the full 3-by-3 shape grid
[elongationGrid, indentationGrid] = ndgrid( ...
    elongations, indentations);
caseOrder = [elongationGrid(:), indentationGrid(:)];
nCase = size(caseOrder, 1);

emptyResult = struct( ...
    'elongation', NaN, ...
    'indentation', NaN, ...
    'converged', false, ...
    'terminationReason', '', ...
    'referenceInnerIterations', NaN, ...
    'outerIterations', NaN, ...
    'functionEvaluations', NaN, ...
    'innerIterations', NaN, ...
    'innerResidual', NaN, ...
    'qMaxRelativeError', NaN, ...
    'qRmsLogError', NaN, ...
    'boundaryError', NaN, ...
    'FFprimeRelativeError', NaN, ...
    'elapsedTime', NaN, ...
    'message', '');

result = repmat(emptyResult, nCase, 1);
equilibria = cell(numel(elongations), numel(indentations));

sweepTimer = tic;

for iCase = 1:nCase
    kappa = caseOrder(iCase, 1);
    indent = caseOrder(iCase, 2);

    fprintf('\nC-shape p-q case %d/%d: kappa = %.1f, indent = %.1f\n', ...
        iCase, nCase, kappa, indent);

    referenceInput = make_indented_reference_input( ...
        R0, aMinor, kappa, delta, indent, B0, ...
        pedge, psiBoundary, nBoundary, NR, NZ, ...
        quadratureDegree, nProfile, pprime, referenceFFprime, ...
        qInteriorPsiN, qContourNR);

    warningState = warning('query', ...
        'GS:QBoundary:ExtrapolationSensitive');
    warning('off', 'GS:QBoundary:ExtrapolationSensitive');
    warningCleanup = onCleanup(@() warning( ...
        warningState.state, 'GS:QBoundary:ExtrapolationSensitive'));
    reference = solve_GS(referenceInput);
    clear warningCleanup

    if ~reference.solverResult.converged
        error('TEST_QSOLVE_INDENTED:ReferenceNonconvergence', ...
            ['The mode-1 reference did not converge at ', ...
             'kappa=%.1f, indent=%.1f.'], kappa, indent);
    end

    qTarget = struct( ...
        'psiN', reference.qResult.psiN, ...
        'q', reference.qResult.q);

    input = make_indented_qsolve_input( ...
        R0, aMinor, kappa, delta, indent, B0, ...
        pedge, psiBoundary, nBoundary, NR, NZ, ...
        quadratureDegree, nProfile, pprime, qTarget, ...
        Fboundary, psiNProfile, initialFFprime, ...
        qInteriorPsiN, qContourNR, tolerance);

    caseTimer = tic;

    try
        equilibrium = solve_GS(input);
        elapsedTime = toc(caseTimer);

        [qMaximum, qRmsLog] = calculate_q_error(equilibrium, 0.95);
        boundaryError = norm( ...
            equilibrium.psi(equilibrium.mesh.boundaryNodes) ...
            -psiBoundary, inf);
        FFprimeRelativeError = norm( ...
            equilibrium.profile.FdF_dpsiN-referenceFFprime, inf) ...
            /max(norm(referenceFFprime, inf), eps);

        caseConverged = ...
            equilibrium.solverResult.converged && ...
            equilibrium.constraintResult.converged && ...
            qMaximum <= tolerance.qConstraintMax*(1+1.0e-10) && ...
            qRmsLog <= tolerance.qConstraintRmsLog*(1+1.0e-10) && ...
            boundaryError < tolerance.boundary;

        result(iCase).elongation = kappa;
        result(iCase).indentation = indent;
        result(iCase).converged = caseConverged;
        result(iCase).terminationReason = ...
            equilibrium.constraintResult.terminationReason;
        result(iCase).referenceInnerIterations = ...
            reference.solverResult.iterations;
        result(iCase).outerIterations = ...
            equilibrium.constraintResult.outerIterations;
        result(iCase).functionEvaluations = ...
            equilibrium.constraintResult.functionEvaluations;
        result(iCase).innerIterations = ...
            equilibrium.solverResult.iterations;
        result(iCase).innerResidual = ...
            equilibrium.solverResult.finalRelativeResidual;
        result(iCase).qMaxRelativeError = qMaximum;
        result(iCase).qRmsLogError = qRmsLog;
        result(iCase).boundaryError = boundaryError;
        result(iCase).FFprimeRelativeError = FFprimeRelativeError;
        result(iCase).elapsedTime = elapsedTime;

        iKappa = find(elongations == kappa, 1);
        iIndent = find(indentations == indent, 1);
        equilibria{iKappa, iIndent} = equilibrium;

        fprintf(['  converged=%d, outer=%d, evaluations=%d, ', ...
                 'max|dq/q|=%.3e, rms(log q/q*)=%.3e, ', ...
                 'FFprime error=%.3e, inner residual=%.3e, ', ...
                 'time=%.1f s\n'], ...
            caseConverged, result(iCase).outerIterations, ...
            result(iCase).functionEvaluations, qMaximum, qRmsLog, ...
            FFprimeRelativeError, result(iCase).innerResidual, ...
            elapsedTime);
    catch ME
        result(iCase).elongation = kappa;
        result(iCase).indentation = indent;
        result(iCase).terminationReason = 'exception';
        result(iCase).elapsedTime = toc(caseTimer);
        result(iCase).message = sprintf('%s: %s', ...
            ME.identifier, ME.message);

        warning('TEST_QSOLVE_INDENTED:CaseFailure', ...
            'kappa=%.1f, indent=%.1f failed: %s', ...
            kappa, indent, result(iCase).message);
    end
end

totalElapsedTime = toc(sweepTimer);

%% Summary and assertions
qsolveIndentedResults = struct2table(result, 'AsArray', true);
disp(qsolveIndentedResults(:, { ...
    'elongation', 'indentation', 'converged', ...
    'outerIterations', 'functionEvaluations', ...
    'qMaxRelativeError', 'qRmsLogError', ...
    'FFprimeRelativeError', 'innerResidual', 'elapsedTime'}));

failed = find(~[result.converged]);

if ~isempty(failed)
    failedDescription = compose('(kappa=%.1f, indent=%.1f, %s)', ...
        [result(failed).elongation].', ...
        [result(failed).indentation].', ...
        string({result(failed).terminationReason}).');

    error('TEST_QSOLVE_INDENTED:Nonconvergence', ...
        'Indented p-q validation failed for: %s', ...
        strjoin(failedDescription, ', '));
end

for iCase = 1:nCase
    kappa = result(iCase).elongation;
    indent = result(iCase).indentation;
    equilibrium = equilibria{ ...
        find(elongations == kappa, 1), ...
        find(indentations == indent, 1)};

    assert(abs(equilibrium.profile.Fpol(end)-Fboundary) ...
            /max(abs(Fboundary), eps) ...
            < tolerance.FboundaryRelative, ...
        'TEST_QSOLVE_INDENTED:FBoundary', ...
        'The fixed-Fb normalization failed at kappa=%.1f, indent=%.1f.', ...
        kappa, indent);

    assert(norm(equilibrium.profile.dp_dpsiN-pprime, inf) ...
            <= tolerance.profileConsistency*max(1, norm(pprime, inf)), ...
        'TEST_QSOLVE_INDENTED:Pprime', ...
        'The prescribed pprime changed at kappa=%.1f, indent=%.1f.', ...
        kappa, indent);

    coefficientStep = ...
        equilibrium.constraintResult.history.coefficientStep;
    assert(any(coefficientStep(isfinite(coefficientStep)) > 100*eps), ...
        'TEST_QSOLVE_INDENTED:ZeroUpdate', ...
        'No nonzero FFprime update was applied at kappa=%.1f, indent=%.1f.', ...
        kappa, indent);
end

if showPlot
    plot_q_sweep(equilibria, elongations, indentations);
end

fprintf('\nIndented C-shape p-q validation passed for all %d cases.\n', ...
    nCase);
fprintf('Total elapsed time = %.1f s\n', totalElapsedTime);
fprintf('Worst max|dq/q|    = %.3e\n', ...
    max([result.qMaxRelativeError]));
fprintf('Worst rms(log q)   = %.3e\n', ...
    max([result.qRmsLogError]));


function input = make_indented_reference_input( ...
    R0, aMinor, kappa, delta, indent, B0, ...
    pedge, psiBoundary, nBoundary, NR, NZ, ...
    quadratureDegree, nProfile, pprime, FFprime, ...
    qInteriorPsiN, qContourNR)
%MAKE_INDENTED_REFERENCE_INPUT Build the known mode-1 reference problem.

    theta = (0:nBoundary-1).'*(2*pi/nBoundary);
    triangularityAngle = asin(delta);
    RBoundary = R0 + aMinor*cos( ...
        theta+triangularityAngle*sin(theta)) ...
        -indent*aMinor*(0.5+0.5*cos(theta)).^3;
    ZBoundary = kappa*aMinor*sin(theta);

    input = struct();
    input.grid = struct( ...
        'nBoundary', nBoundary, 'NR', NR, 'NZ', NZ, ...
        'quadratureDegree', quadratureDegree, 'nProfile', nProfile);
    input.dim = struct('R0', R0, 'B0', B0, 'aMinor', aMinor);
    input.boundary = struct( ...
        'R', RBoundary, 'Z', ZBoundary, ...
        'psiBoundary', psiBoundary);
    input.Picard = struct( ...
        'omega', 0.5, 'maxIterations', 250, ...
        'updateTolerance', 2.0e-7, ...
        'residualTolerance', 5.0e-7, ...
        'axisMode', 'max', ...
        'symmetryTolerance', 1.0e-12, ...
        'fluxSpanTolerance', 1.0e-12);
    input.profile = struct( ...
        'mode', 1, 'pprime', pprime, ...
        'FFprime', FFprime, 'pedge', pedge);
    input.qEvaluation = struct( ...
        'interiorPsiN', qInteriorPsiN, 'contourNR', qContourNR);
    input.output = struct( ...
        'verbose', false, 'checkTime', false, 'showPlot', false);
end


function input = make_indented_qsolve_input( ...
    R0, aMinor, kappa, delta, indent, B0, ...
    pedge, psiBoundary, nBoundary, NR, NZ, ...
    quadratureDegree, nProfile, pprime, qTarget, ...
    Fboundary, initialPsiN, initialFFprime, ...
    qInteriorPsiN, qContourNR, tolerance)
%MAKE_INDENTED_QSOLVE_INPUT Build one C-shape mode-3 input structure.

    theta = (0:nBoundary-1).'*(2*pi/nBoundary);
    triangularityAngle = asin(delta);

    RBoundary = R0 + aMinor*cos( ...
        theta+triangularityAngle*sin(theta)) ...
        -indent*aMinor*(0.5+0.5*cos(theta)).^3;
    ZBoundary = kappa*aMinor*sin(theta);

    if any(RBoundary <= 0)
        error('TEST_QSOLVE_INDENTED:InvalidBoundary', ...
            'The C-shape boundary contains R <= 0.');
    end

    input = struct();
    input.grid = struct( ...
        'nBoundary', nBoundary, ...
        'NR', NR, ...
        'NZ', NZ, ...
        'quadratureDegree', quadratureDegree, ...
        'nProfile', nProfile);
    input.dim = struct( ...
        'R0', R0, ...
        'B0', B0, ...
        'aMinor', aMinor);
    input.boundary = struct( ...
        'R', RBoundary, ...
        'Z', ZBoundary, ...
        'psiBoundary', psiBoundary);
    input.Picard = struct( ...
        'omega', 0.5, ...
        'maxIterations', 250, ...
        'updateTolerance', 2.0e-7, ...
        'residualTolerance', 5.0e-7, ...
        'axisMode', 'max', ...
        'symmetryTolerance', 1.0e-12, ...
        'fluxSpanTolerance', 1.0e-12);

    input.profile = struct();
    input.profile.mode = 3;
    input.profile.pprime = pprime;
    input.profile.q = qTarget;
    input.profile.pedge = pedge;
    input.profile.normalization = struct( ...
        'mode', 'fixed_Fb', ...
        'Fb', Fboundary);
    input.profile.FSign = sign(Fboundary);
    input.profile.initial = struct( ...
        'type', 'FFprime', ...
        'psiN', initialPsiN, ...
        'FFprime', initialFFprime);

    input.pqConstraint = struct();
    input.pqConstraint.outer = struct( ...
        'maxIterations', 20, ...
        'qRelativeTolerance', tolerance.qConstraintMax, ...
        'qRmsLogTolerance', tolerance.qConstraintRmsLog, ...
        'minimumIterations', 2, ...
        'minimumQPoints', 3, ...
        'stopOnInnerNonconvergence', true, ...
        'errorOnFailure', false, ...
        'storePsiHistory', false, ...
        'verbose', false);
    input.pqConstraint.FFprime = struct( ...
        'nBasis', 3, ...
        'enforceZeroEdge', false, ...
        'regularization', 1.0e-9, ...
        'jacobianRidge', 1.0e-11, ...
        'initialDamping', 1.0e-3, ...
        'maxCoefficientStep', 5.0, ...
        'initialScales', 1.0, ...
        'fitRange', [0, 0.95], ...
        'axisWeight', 1.0);

    input.qEvaluation = struct( ...
        'interiorPsiN', qInteriorPsiN, ...
        'contourNR', qContourNR);
    input.output = struct( ...
        'verbose', false, ...
        'checkTime', false, ...
        'showPlot', false);
end


function [maximumRelative, rmsLog] = ...
    calculate_q_error(equilibrium, fitMaximum)
%CALCULATE_Q_ERROR Recompute the exact outer convergence metrics.

    psiN = equilibrium.qGeometry.psiN(:);
    qCalculated = equilibrium.qResult.q(:);
    qTarget = equilibrium.profile.qPrescribed.q(:);
    qPerF = equilibrium.qGeometry.qPerF(:);

    valid = isfinite(psiN) & isfinite(qCalculated) ...
        &isfinite(qTarget) & isfinite(qPerF) ...
        &qTarget ~= 0 & psiN <= fitMaximum;

    relativeError = ...
        (qCalculated(valid)-qTarget(valid))./qTarget(valid);
    logError = log(abs(qCalculated(valid)./qTarget(valid)));

    maximumRelative = max(abs(relativeError));
    rmsLog = sqrt(mean(logError.^2));
end


function plot_q_sweep(equilibria, elongations, indentations)
%PLOT_Q_SWEEP Compare prescribed and reconstructed q for every shape.

    figure('Color', 'w', 'Name', 'Indented C-shape p-q validation');
    layout = tiledlayout( ...
        numel(elongations), numel(indentations), ...
        'TileSpacing', 'compact', 'Padding', 'compact');
    firstAxes = [];

    for iKappa = 1:numel(elongations)
        for iIndent = 1:numel(indentations)
            equilibrium = equilibria{iKappa, iIndent};
            axesHandle = nexttile;

            if isempty(firstAxes)
                firstAxes = axesHandle;
            end

            plot(equilibrium.profile.qPrescribed.psiN, ...
                equilibrium.profile.qPrescribed.q, ...
                'k-', 'LineWidth', 1.5);
            hold on;
            plot(equilibrium.qResult.psiN, equilibrium.qResult.q, ...
                'o-', 'LineWidth', 1.0, 'MarkerSize', 3);
            grid on;
            xlim([0, 1]);
            title(sprintf('\\kappa=%.1f, indent=%.1f', ...
                elongations(iKappa), indentations(iIndent)));

            if iKappa == numel(elongations)
                xlabel('\psi_N');
            end
            if iIndent == 1
                ylabel('q');
            end
        end
    end

    legend(firstAxes, {'target', 'calculated'}, ...
        'Location', 'best');
    title(layout, 'Prescribed versus reconstructed q');
end
