function report = verify_geometry(doPlot)
%VERIFY_GEOMETRY Run deterministic checks for boundary and mesh generation.
%
%   REPORT = VERIFY_GEOMETRY() checks a circle, harmonic C-shape, localized
%   extreme C-shape, pointed boomerang C-shape, third-harmonic cosine
%   C-shape, and a Miller D-shape, then prints mesh diagnostics and plots.
%   REPORT = VERIFY_GEOMETRY(false) performs the same checks without plots.

if nargin < 1
    doPlot = true;
end
validateattributes(doPlot, {'logical', 'numeric'}, ...
    {'real', 'finite', 'scalar'}, mfilename, 'doPlot');
doPlot = logical(doPlot);

cases(1).name = 'circle';
cases(1).params = struct( ...
    'A', 3.0, 'B', 1.0, 'C', 0.0, ...
    'G', 1.0, 'H', 0.0, 'nBoundary', 96);
cases(1).targetH = 0.18;

cases(2).name = 'harmonic C-shape';
cases(2).params = struct( ...
    'A', 3.0, 'B', 0.9, 'C', 0.34, ...
    'G', 1.1, 'H', 0.10, 'nBoundary', 160);
cases(2).targetH = 0.12;

cases(3).name = 'localized C-shape';
cases(3).params = struct( ...
    'type', 'localized-c', ...
    'A', 3.0, 'B', 0.9, 'D', 1.1, 'beta', 0.9, ...
    'G', 1.3298, 'H', 0.0, 'nBoundary', 240);
cases(3).targetH = 0.08;

cases(4).name = 'boomerang C-shape';
cases(4).params = struct( ...
    'type', 'boomerang-c', 'A', 3.0, ...
    'Rback', 2.0, 'Rtip', 2.65, 'Rend', 3.8, 'Zend', 2.7, ...
    'pInner', 1.6, 'pOuter', 1.4, 'nBoundary', 320);
cases(4).targetH = 0.08;

cases(5).name = 'cosine C-shape';
cases(5).params = struct( ...
    'type', 'cosine-c', 'R0', 3.0, ...
    'A', 0.8, 'B', -1.0, 'C', 0.0, 'kappa', 4.0, ...
    'nBoundary', 320);
cases(5).targetH = 0.08;

cases(6).name = 'Miller D-shape';
cases(6).params = struct( ...
    'type','miller-d','R0',3.0,'a',3/3.17, ...
    'kappa',1.66,'delta',0.416,'nBoundary',256);
cases(6).targetH = 0.08;

tabulatedAngle = linspace(0,2*pi,97).';
cases(7).name = 'tabulated LCFS';
cases(7).params = struct('type','tabulated', ...
    'R',1.8+0.5*cos(tabulatedAngle), ...
    'Z',0.75*sin(tabulatedAngle),'nBoundary',128);
cases(7).targetH = 0.08;

report = repmat(struct(), numel(cases), 1);

for k = 1:numel(cases)
    geom = make_boundary(cases(k).params);
    meshData = generate_mesh(geom, ...
        struct('targetH', cases(k).targetH));

    assert(geom.RLim(1) > 0, 'LCFS must remain at R > 0.');
    assert(meshData.quality.relativeAreaError < 1e-8, ...
        'The mesh must reproduce the polygon area.');
    assert(all(meshData.elementArea > 0), ...
        'Every element must have counterclockwise orientation.');
    assert(numel(meshData.boundaryNodes) == geom.nBoundary, ...
        'Every sampled LCFS node must be retained.');

    if strcmp(cases(k).name, 'circle')
        analyticArea = pi*cases(k).params.B*cases(k).params.G;
        relativePolygonError = abs(geom.area-analyticArea)/analyticArea;
        assert(relativePolygonError < 1e-3, ...
            'The sampled circular boundary area is unexpectedly inaccurate.');
        assert(~geom.isConcave, 'The circle was incorrectly marked concave.');
    elseif ismember(cases(k).name,{'Miller D-shape','tabulated LCFS'})
        assert(~geom.isConcave, ...
            'The convex boundary was incorrectly marked concave.');
    else
        assert(geom.isConcave, ...
            'The C-shape verification case must contain a concave segment.');
    end
    if strcmp(cases(k).name, 'localized C-shape')
        assert(abs(geom.outboardMidplaneR-2.8) < 1e-13, ...
            'The localized indentation tip is incorrect.');
        assert(geom.tipInsideNominalMajorRadius, ...
            'The localized tip must lie inside the nominal major radius.');
        assert(abs(geom.boundingBoxElongation-3) < 2e-3, ...
            'The localized verification elongation is not approximately 3.');
    end
    if strcmp(cases(k).name, 'boomerang C-shape')
        assert(abs(geom.outboardMidplaneR-2.65) < 1e-13, ...
            'The boomerang indentation tip is incorrect.');
        assert(geom.tipInsideNominalMajorRadius, ...
            'The boomerang indentation must lie inside nominal major radius.');
        assert(abs(geom.boundingBoxElongation-3) < 1e-13, ...
            'The boomerang verification elongation must equal 3.');
        assert(geom.hasPointedEnds, ...
            'The boomerang endpoints must be marked pointed.');
        assert(abs(geom.endPointR-3.8) < 1e-13 && ...
               abs(geom.endPointZ-2.7) < 1e-13, ...
            'The boomerang endpoint location is incorrect.');
    end
    if strcmp(cases(k).name, 'cosine C-shape')
        assert(abs(geom.outboardMidplaneR-2.8) < 1e-13, ...
            'The cosine-boundary indentation tip is incorrect.');
        assert(abs(geom.endPointR-4.0) < 1e-13 && ...
               abs(geom.endPointZ-3.2) < 1e-13, ...
            'The cosine-boundary upper/lower point is incorrect.');
        assert(abs(geom.verticalHeight-2*4.0*0.8) < 1e-12, ...
            'The cosine-boundary vertical height is incorrect.');
        assert(geom.tipInsideNominalMajorRadius, ...
            'The cosine-boundary tip must lie inside R0.');
        assert(~geom.hasPointedEnds, ...
            'C=0 must produce rounded rather than cusped endpoints.');
        assert(abs(geom.outboardMidplaneCurvatureRadius-3.2) < 1e-12, ...
            'The cosine-boundary midplane curvature radius is incorrect.');
    end
    if strcmp(cases(k).name,'Miller D-shape')
        params = cases(k).params;
        assert(abs(geom.outboardMidplaneR-(params.R0+params.a))<1e-12, ...
            'The Miller outboard radius is incorrect.');
        assert(abs(geom.endPointR-(params.R0-params.a*params.delta))<1e-12, ...
            'The Miller top-point triangularity is incorrect.');
        assert(abs(geom.boundingBoxElongation-params.kappa)<2e-3, ...
            'The Miller elongation is incorrect.');
    end

    report(k).name = cases(k).name;
    report(k).nNodes = meshData.nNodes;
    report(k).nElements = meshData.nElements;
    report(k).isConcave = geom.isConcave;
    report(k).elongation = geom.boundingBoxElongation;
    report(k).nominalElongation = geom.nominalElongation;
    report(k).outboardMidplaneR = geom.outboardMidplaneR;
    report(k).endPointR = geom.endPointR;
    report(k).endPointZ = geom.endPointZ;
    report(k).minimumQuality = meshData.quality.minimum;
    report(k).meanQuality = meshData.quality.mean;
    report(k).relativeAreaError = meshData.quality.relativeAreaError;

    fprintf(['%-16s nodes=%5d, elements=%5d, concave=%d, ' ...
             'q_min=%.3f, area_error=%.3e\n'], ...
        report(k).name, report(k).nNodes, report(k).nElements, ...
        report(k).isConcave, report(k).minimumQuality, ...
        report(k).relativeAreaError);

    if doPlot
        figure('Name',sprintf('Geometry verification: %s', ...
            cases(k).name),'Color','w');
        triplot(meshData.elements, meshData.nodes(:,1), ...
            meshData.nodes(:,2), 'Color', [0.72, 0.78, 0.84]);
        hold on
        plot(geom.closedPoints(:,1), geom.closedPoints(:,2), ...
            'k-', 'LineWidth', 1.8);
        plot(geom.centroid(1), geom.centroid(2), 'r+', ...
            'MarkerSize', 8, 'LineWidth', 1.2);
        hold off
        axis equal tight
        grid on
        xlabel('R');
        ylabel('Z');
        title(sprintf(['%s: %d nodes, %d elements, ' ...
            'q_{min}=%.3f'],cases(k).name,meshData.nNodes, ...
            meshData.nElements,meshData.quality.minimum));
    end
end

fprintf('geometry verification passed.\n');

end
