clc
clear
close all

thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);
addpath(fullfile(thisDir, '..', 'Gaur'));

p = DshapeMillerParams();

% Miller Fig. 5 style: vary delta only. Other Miller parameters, including
% s_delta, are kept fixed.
deltaGrid = [0.1, 0.3, 0.5, 0.7];

% Coarse scan for a first pass. Increase these after the curve locations are
% identified.
ns = 20; nalpha = 20; ntheta0 = 30;
sGrid = linspace(0.0, 5.0, ns);
alphaGrid = linspace(0.0, 8.0, nalpha);
theta0Grid = linspace(0.0, pi, ntheta0);

outDelta = scan_miller_delta_salpha_curves(p, ...
    'DeltaGrid', deltaGrid, ...
    'SGrid', sGrid, ...
    'AlphaGrid', alphaGrid, ...
    'Theta0Grid', theta0Grid, ...
    'NThetaCoeff', 161, ...
    'NGeom', 601, ...
    'ThetaB', 5*pi, ...
    'NBalloon', 201, ...
    'NEigs', 6, ...
    'UseParallel', true, ...
    'PoolType', 'threads', ...
    'Verbose', true);

plot_miller_delta_marginal_curves(outDelta);

fprintf('Miller delta s-alpha marginal-curve scan done.\n');
for id = 1:numel(outDelta.delta)
    lam = outDelta.scans{id}.lambda_max;
    fprintf('  delta = %.4g: lambda range %.6g to %.6g\n', ...
        outDelta.delta(id), ...
        min(lam(:), [], 'omitnan'), ...
        max(lam(:), [], 'omitnan'));
end
