clc
clear
close all

%% Load GEQDSK local-equilibrium ballooning solver
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);
addpath(fullfile(thisDir, '..', 'Gaur'));

geqdskFile = fullfile(thisDir, 'geqdsk_circular');

% Choose the flux surface here.  Keep Dpsin below safely inside [0, 1].
psin0 = 0.80;

% Coarse first-pass scan.  Increase ns/nalpha/ntheta0 after the marginal
% curve location is identified.
ns = 30;
nalpha = 30;
ntheta0 = 15;
sGrid = linspace(0.0, 7.0, ns);
alphaGrid = linspace(0.0, 10.0, nalpha);
theta0Grid = linspace(0.0, pi, ntheta0);

out = scan_geqdsk_salpha_diagram(geqdskFile, psin0, ...
    'SGrid', sGrid, ...
    'AlphaGrid', alphaGrid, ...
    'Theta0Grid', theta0Grid, ...
    'JacMode', 4, ...
    'NThetaCoeff', 128, ...
    'Dpsin', 1e-3, ...
    'ShearDefinition', 'flux', ...
    'ThetaB', 5*pi, ...
    'NBalloon', 151, ...
    'NEigs', 4, ...
    'Verbose', true);

plot_salpha_diagram(out, ...
    'MarginalMode', 'curves', ...
    'Title', sprintf('Circular GEQDSK local $s$-$\\alpha$ diagram, $\\psi_N=%.3g$', psin0));

fprintf('Circular GEQDSK s-alpha scan done.\n');
fprintf('  file        : %s\n', geqdskFile);
fprintf('  psin        : %.6g\n', psin0);
fprintf('  alphaFactor : %.12e\n', out.alphaFactor);
fprintf('  lambda range: %.6g to %.6g\n', ...
    min(out.lambda_max(:), [], 'omitnan'), ...
    max(out.lambda_max(:), [], 'omitnan'));
