clc
clear
close all

thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);
addpath(fullfile(thisDir, '..', 'Gaur'));

p = DshapeMillerParams();

% Coarse default scan. Increase these grids after the marginal curve appears.
ns = 20; nalpha = 20; ntheta0 = 5;
sGrid = linspace(0.0, 7.0, ns);
alphaGrid = linspace(0.0, 8.0, nalpha);
theta0Grid = linspace(0.0, pi, ntheta0);

out = scan_miller_salpha_diagram(p, ...
    'SGrid', sGrid, ...
    'AlphaGrid', alphaGrid, ...
    'Theta0Grid', theta0Grid, ...
    'NThetaCoeff', 161, ...
    'NGeom', 601, ...
    'ThetaB', 5*pi, ...
    'NBalloon', 201, ...
    'NEigs', 6, ...
    'Verbose', true);

plot_salpha_diagram(out);

fprintf('Miller D-shape s-alpha scan done.\n');
fprintf('lambda_max range: %.6g to %.6g\n', ...
    min(out.lambda_max(:), [], 'omitnan'), ...
    max(out.lambda_max(:), [], 'omitnan'));
