clc
clear
close all

%% Load ballooning solver
thisDir = fileparts(mfilename('fullpath'));
addpath(thisDir);
addpath(fullfile(thisDir, '..', 'Gaur'));

eq = read_geqdsk('./geqdsk_PT0.7');

psiN = 0.77;
p = fit_Miller(eq, psiN, 'dpsi', 1.e-3, 'NTheta', 600);

% Vary elongation only. Other Miller parameters, including s_kappa, are kept
% fixed while each kappa value is scanned over the s-alpha diagram.
kappaGrid = [1.4, 1.6, 1.8];

% Coarse scan for a first pass. Increase these after the curve locations are
% identified.
ns = 30; nalpha = 30; ntheta0 = 15;
sGrid = linspace(0.0, 7.0, ns);
alphaGrid = linspace(0.0, 12.0, nalpha);
theta0Grid = linspace(0.0, pi, ntheta0);

outKappa = scan_miller_delta_salpha_curves(p, ...
    'ScanParameter', 'kappa', ...
    'KappaGrid', kappaGrid, ...
    'SGrid', sGrid, ...
    'AlphaGrid', alphaGrid, ...
    'Theta0Grid', theta0Grid, ...
    'NThetaCoeff', 161, ...
    'NGeom', 601, ...
    'ThetaB', 5*pi, ...
    'NBalloon', 201, ...
    'NEigs', 6, ...
    'UseParallel', true, ...
    'PoolType', 'threads', ...
    'Verbose', true);

plot_miller_delta_marginal_curves(outKappa, ...
    'MarginalMode', 'contour', ...
    'ShowLegend', true);

fprintf('Miller kappa s-alpha marginal-curve scan done.\n');
for id = 1:numel(outKappa.kappa)
    lam = outKappa.scans{id}.lambda_max;
    fprintf('  kappa = %.4g: lambda range %.6g to %.6g\n', ...
        outKappa.kappa(id), ...
        min(lam(:), [], 'omitnan'), ...
        max(lam(:), [], 'omitnan'));
end

ax = gca;
ax.Children = flipud(ax.Children);
lgd = legend;
labels = lgd.String;
legend(flip(labels));