%% Fixed-boundary Grad-Shafranov solver: third-harmonic cosine C-shape
% Boundary definition:
%   R = R0 + A*cos(theta) + B*cos(2*theta) + C*cos(3*theta),
%   Z = kappa*A*sin(theta).
%
% The default target is a verified nonlinear, single-axis reference case.
% B<0 moves both midplane crossings inward and the upper/lower points
% outward. The script starts from an ellipse and follows the equilibrium
% through continuation rather than prescribing any interior flux surfaces.

clear
clc
close all

projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot,'geometry'), ...
        fullfile(projectRoot,'fem'), ...
        fullfile(projectRoot,'physics'), ...
        fullfile(projectRoot,'solver'), ...
        fullfile(projectRoot,'post'));

%% User configuration
cfg = struct();

% The starting ellipse has B=C=0. The target has an inward-shifted
% midplane and outward-shifted upper/lower points.
cfg.startBoundary = struct( ...
    'type','cosine-c', ...
    'R0',3.0,'A',0.8,'B',0.0,'C',0.0, ...
    'kappa',1.5,'nBoundary',160);
cfg.targetBoundary = struct( ...
    'type','cosine-c', ...
    'R0',3.0,'A',0.8,'B',-1.0,'C',0.0, ...
    'kappa',4.0,'nBoundary',320);
% Curvature-scan alternative (actual elongation about 3, lower bad share):
cfg.targetBoundary = struct('type','cosine-c', ...
    'R0',3.0,'A',0.32,'B',-0.55,'C',0.032, ...
    'kappa',6.8604,'nBoundary',320);
cfg.continuationLambdas = (0:0.05:1).';

% Refined resolution used by the local flux-surface/ballooning pipeline.
% The P1 flux contours become visibly polygonal on the coarser targetH=0.08
% mesh even if their output sampling count is increased afterward.
cfg.mesh = struct('targetH',0.05,'boundaryClearance',0.12);

% Nonlinear reference profiles. These are not fitted experimental profiles.
cfg.profiles = make_profiles(struct( ...
    'pprime',struct('type','normalized-power', ...
                    'axisValue',-8.0e5,'exponent',2.0), ...
    'FFprime',struct('type','normalized-power', ...
                     'axisValue',-0.8,'exponent',1.0)));

cfg.initialGuess = struct('boundaryValue',0.0,'axisValue',-1.0);
cfg.picard = struct( ...
    'tolerance',1e-8, ...
    'residualTolerance',2e-8, ...
    'maxIterations',1200, ...
    'omega',0.2, ...
    'boundaryValue',0.0, ...
    'axisMode','min', ...
    'updateFluxAxis',true, ...
    'failOnNonconvergence',true, ...
    'verbose',false);

cfg.topologyLevels = (0.1:0.1:0.9).';
cfg.FBoundary = 3.0;
cfg.makePlots = true;

%% Nonlinear continuation into the cosine C-shape
continuationOptions = struct( ...
    'mesh',cfg.mesh, ...
    'initialGuess',cfg.initialGuess, ...
    'picard',cfg.picard, ...
    'verbose',true);

continuation = solve_continuation( ...
    cfg.startBoundary,cfg.targetBoundary, ...
    cfg.continuationLambdas,cfg.profiles,continuationOptions);

geom = continuation.finalGeometry;
mesh = continuation.finalMesh;
psi = continuation.finalPsi;
solverResult = continuation.finalSolver;

%% Axis and topology diagnostics
axisData = find_axis(mesh,psi,struct( ...
    'mode',cfg.picard.axisMode, ...
    'boundaryValue',cfg.picard.boundaryValue));

topology = check_topology(mesh,psi,axisData,struct( ...
    'normalizedLevels',cfg.topologyLevels, ...
    'boundaryValue',cfg.picard.boundaryValue, ...
    'failOnFailure',false, ...
    'requireSingleO',true, ...
    'requireNoX',true));

if ~topology.passed
    warning('GS:mainCos:TopologyCheckFailed', ...
        ['The FEM solve converged, but the single-axis topology check ' ...
         'failed. Inspect equilibrium.topology before using the result.']);
end

%% Magnetic-field reconstruction
FFspec = cfg.profiles.FFprime;
FofPsi = @(psiValue) reconstruct_F_cos(psiValue,axisData.psi, ...
    cfg.picard.boundaryValue,cfg.FBoundary, ...
    FFspec.axisValue,FFspec.exponent);
field = compute_B(mesh,psi,FofPsi);
curvature = compute_magnetic_curvature( ...
    mesh,psi,field,cfg.profiles,struct( ...
        'psiAxis',axisData.psi, ...
        'boundaryValue',cfg.picard.boundaryValue, ...
        'projectPerpendicular',true, ...
        'normalizedFluxEdges',(0:0.1:1).'));

shape = struct();
shape.R0 = geom.nominalMajorRadius;
shape.A = geom.params.A;
shape.B = geom.params.B;
shape.C = geom.params.C;
shape.kappa = geom.params.kappa;
shape.midplaneOuterR = geom.outboardMidplaneR;
shape.midplaneInnerR = geom.inboardMidplaneR;
shape.upperLowerR = geom.endPointR;
shape.upperLowerAbsZ = geom.endPointZ;
shape.nominalElongation = geom.nominalElongation;
shape.boundingBoxElongation = geom.boundingBoxElongation;
shape.indentationCurvatureRadius = ...
    geom.outboardMidplaneCurvatureRadius;
shape.tipInsideR0 = geom.tipInsideNominalMajorRadius;
shape.tipInsideMagneticAxis = geom.outboardMidplaneR < axisData.R;

%% Collect result
equilibrium = struct();
equilibrium.configuration = cfg;
equilibrium.geometry = geom;
equilibrium.mesh = mesh;
equilibrium.psi = psi;
equilibrium.profiles = cfg.profiles;
equilibrium.solver = solverResult;
equilibrium.continuation = continuation;
equilibrium.axis = axisData;
equilibrium.topology = topology;
equilibrium.field = field;
equilibrium.curvature = curvature;
equilibrium.cosineShape = shape;

%% Text summary
nSteps = numel(continuation.steps);
lambda = zeros(nSteps,1);
nNodes = zeros(nSteps,1);
nElements = zeros(nSteps,1);
nPicard = zeros(nSteps,1);
finalResidual = zeros(nSteps,1);
psiAxis = zeros(nSteps,1);
for k = 1:nSteps
    lambda(k) = continuation.steps(k).lambda;
    nNodes(k) = continuation.steps(k).mesh.nNodes;
    nElements(k) = continuation.steps(k).mesh.nElements;
    nPicard(k) = continuation.steps(k).solver.nIterations;
    finalResidual(k) = continuation.steps(k).solver.finalResidual;
    psiAxis(k) = continuation.steps(k).solver.axisValue;
end
continuationTable = table(lambda,nNodes,nElements,nPicard, ...
    finalResidual,psiAxis);

fprintf('\nCosine C-shape Grad-Shafranov solve complete.\n')
disp(continuationTable)
fprintf('Final magnetic axis : R = %.8f, Z = %.8f, psi = %.8g\n', ...
    axisData.R,axisData.Z,axisData.psi)
fprintf('Final Picard solve  : %d iterations, residual = %.3e\n', ...
    solverResult.nIterations,solverResult.finalResidual)
fprintf('Flux topology       : passed = %d, O-points = %d, X-points = %d\n', ...
    topology.passed,topology.nOPoints,topology.nXPoints)
fprintf('Final mesh          : %d nodes, %d P1 elements\n', ...
    mesh.nNodes,mesh.nElements)
fprintf(['Cosine parameters   : R0 = %.4f, A = %.4f, B = %.4f, ' ...
         'C = %.4f, kappa = %.4f\n'], ...
    shape.R0,shape.A,shape.B,shape.C,shape.kappa)
fprintf(['Shape locations     : R_mid,out = %.6f, R_mid,in = %.6f, ' ...
         '(R_upper, |Z_upper|) = (%.6f, %.6f)\n'], ...
    shape.midplaneOuterR,shape.midplaneInnerR, ...
    shape.upperLowerR,shape.upperLowerAbsZ)
fprintf(['Elongation          : nominal kappa = %.6f, ' ...
         'actual bounding-box = %.6f\n'], ...
    shape.nominalElongation,shape.boundingBoxElongation)
fprintf('Indent curvature R  : %.6f m\n', ...
    shape.indentationCurvatureRadius)
fprintf(['Indentation checks  : R_mid,out < R0 = %d, ' ...
         'R_mid,out < magnetic-axis R = %d\n\n'], ...
    shape.tipInsideR0,shape.tipInsideMagneticAxis)
fprintf(['Curvature magnitude : min = %.6e 1/m, max = %.6e 1/m, ' ...
         'area mean = %.6e 1/m\n'], ...
    curvature.statistics.minimumKappaMagnitude, ...
    curvature.statistics.maximumKappaMagnitude, ...
    curvature.statistics.areaWeightedMeanKappaMagnitude)
fprintf(['kappa dot grad(p)   : min = %.6e, max = %.6e, ' ...
         'toroidal-volume mean = %.6e\n'], ...
    curvature.statistics.minimumKappaDotGradP, ...
    curvature.statistics.maximumKappaDotGradP, ...
    curvature.statistics.volumeWeightedMeanKappaDotGradP)
fprintf(['Signed volume share : positive = %.4f, negative = %.4f, ' ...
         'near zero = %.4f\n\n'], ...
    curvature.statistics.positiveVolumeFraction, ...
    curvature.statistics.negativeVolumeFraction, ...
    curvature.statistics.nearZeroVolumeFraction)
disp(curvature.statistics.fluxBands)

%% Plots
if cfg.makePlots
    plot_flux(mesh,psi,struct( ...
        'axisData',axisData, ...
        'normalizedLevels',cfg.topologyLevels, ...
        'boundaryValue',cfg.picard.boundaryValue, ...
        'title','Third-harmonic cosine C-shape equilibrium'));

    figure('Name','Cosine boundary continuation','Color','w')
    colorMap = parula(nSteps);
    hold on
    for k = 1:nSteps
        boundary = continuation.steps(k).geom.closedPoints;
        plot(boundary(:,1),boundary(:,2),'-', ...
            'Color',colorMap(k,:),'LineWidth',1.3, ...
            'DisplayName',sprintf('lambda = %.2f',lambda(k)))
    end
    plot(shape.midplaneOuterR,0,'ro','MarkerFaceColor','r', ...
        'DisplayName','outer-midplane indentation')
    plot([shape.upperLowerR;shape.upperLowerR], ...
         [-shape.upperLowerAbsZ;shape.upperLowerAbsZ], ...
         'ks','MarkerFaceColor','y','DisplayName','upper/lower points')
    hold off
    axis equal tight
    grid on
    xlabel('R')
    ylabel('Z')
    title('Continuation into the cosine C-shape')
    legend('Location','bestoutside')

    figure('Name','Picard convergence','Color','w')
    semilogy(1:solverResult.nIterations,solverResult.updateHistory, ...
        '-','LineWidth',1.6)
    hold on
    semilogy(1:solverResult.nIterations,solverResult.residualHistory, ...
        '--','LineWidth',1.6)
    hold off
    grid on
    xlabel('Picard iteration')
    ylabel('Relative measure')
    legend('iterate update','equation residual','Location','best')
    title('Final continuation-step convergence')

    figure('Name','Poloidal magnetic field','Color','w')
    trisurf(mesh.elements,mesh.nodes(:,1),mesh.nodes(:,2), ...
        field.node.Bp,'EdgeColor','none','FaceColor','interp')
    view(2)
    axis equal tight
    grid on
    colorbar
    xlabel('R')
    ylabel('Z')
    title('|B_p| on the final cosine C-shape mesh')

    plot_curvature(mesh,curvature,struct( ...
        'titlePrefix',['Cosine C-shape: ' ...
                       '\kappa\cdot\nabla p ' ...
                       '(dashed: zero boundary)']));
end


function F = reconstruct_F_cos(psi,psiAxis,psiBoundary,FBoundary, ...
        FFaxisValue,exponent)
% Integrate FF'=F*dF/dpsi for FF'=C*(1-psi_N)^exponent.
span = psiBoundary-psiAxis;
psiNormalized = (psi-psiAxis)/span;
psiNormalized = min(max(psiNormalized,0),1);
F2 = FBoundary^2 ...
   -2*FFaxisValue*span/(exponent+1) ...
    .*(1-psiNormalized).^(exponent+1);
if any(F2(:)<=0)
    error('GS:mainCos:NonPositiveFSquared', ...
        ['The selected FBoundary and FFprime profile produce F^2<=0. ' ...
         'Increase FBoundary or reduce the FFprime amplitude.']);
end
F = sqrt(F2);
end
