%% Fixed-boundary Grad-Shafranov solver: Miller D-shaped LCFS
% Boundary definition:
%   R = R0 + a*cos(theta + asin(delta)*sin(theta)),
%   Z = kappa*a*sin(theta).
%
% The target uses the standard Miller-paper aspect ratio and shaping
% (R0/a=3.17, kappa=1.66, delta=0.416), scaled to R0=3 m. The pressure and
% FF' profiles, mesh target, and nonlinear solver settings match main_cos
% so the subsequent local ballooning scans can be compared directly.

clear
clc
close all

projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot,'geometry'), ...
        fullfile(projectRoot,'fem'), ...
        fullfile(projectRoot,'physics'), ...
        fullfile(projectRoot,'solver'), ...
        fullfile(projectRoot,'post'));

%% User configuration
cfg = struct();
R0 = 3.0;
minorRadius = R0/3.17;
cfg.startBoundary = struct('type','miller-d', ...
    'R0',R0,'a',minorRadius,'kappa',1.0,'delta',0.0, ...
    'nBoundary',160);
cfg.targetBoundary = struct('type','miller-d', ...
    'R0',R0,'a',minorRadius,'kappa',1.66,'delta',0.416, ...
    'nBoundary',320);
cfg.continuationLambdas = (0:0.1:1).';

cfg.mesh = struct('targetH',0.05,'boundaryClearance',0.12);
cfg.profiles = make_profiles(struct( ...
    'pprime',struct('type','normalized-power', ...
                    'axisValue',-8.0e5,'exponent',2.0), ...
    'FFprime',struct('type','normalized-power', ...
                     'axisValue',-0.8,'exponent',1.0)));

cfg.initialGuess = struct('boundaryValue',0.0,'axisValue',-1.0);
cfg.picard = struct( ...
    'tolerance',1e-8, ...
    'residualTolerance',2e-8, ...
    'maxIterations',1200, ...
    'omega',0.2, ...
    'boundaryValue',0.0, ...
    'axisMode','min', ...
    'updateFluxAxis',true, ...
    'failOnNonconvergence',true, ...
    'verbose',false);

cfg.topologyLevels = (0.1:0.1:0.9).';
cfg.FBoundary = 14;
cfg.makePlots = true;

%% Nonlinear continuation from a circle to the Miller D-shape
continuationOptions = struct( ...
    'mesh',cfg.mesh, ...
    'initialGuess',cfg.initialGuess, ...
    'picard',cfg.picard, ...
    'verbose',true);

continuation = solve_continuation( ...
    cfg.startBoundary,cfg.targetBoundary, ...
    cfg.continuationLambdas,cfg.profiles,continuationOptions);

geom = continuation.finalGeometry;
mesh = continuation.finalMesh;
psi = continuation.finalPsi;
solverResult = continuation.finalSolver;

%% Axis, topology, and magnetic-field diagnostics
axisData = find_axis(mesh,psi,struct( ...
    'mode',cfg.picard.axisMode, ...
    'boundaryValue',cfg.picard.boundaryValue));

topology = check_topology(mesh,psi,axisData,struct( ...
    'normalizedLevels',cfg.topologyLevels, ...
    'boundaryValue',cfg.picard.boundaryValue, ...
    'failOnFailure',false, ...
    'requireSingleO',true, ...
    'requireNoX',true));
if ~topology.passed
    warning('GS:mainMiller:TopologyCheckFailed', ...
        ['The FEM solve converged, but the single-axis topology check ' ...
         'failed. Inspect equilibrium.topology before using the result.']);
end

FFspec = cfg.profiles.FFprime;
FofPsi = @(psiValue) reconstruct_F_miller( ...
    psiValue,axisData.psi,cfg.picard.boundaryValue, ...
    cfg.FBoundary,FFspec.axisValue,FFspec.exponent);
field = compute_B(mesh,psi,FofPsi);
curvature = compute_magnetic_curvature( ...
    mesh,psi,field,cfg.profiles,struct( ...
        'psiAxis',axisData.psi, ...
        'boundaryValue',cfg.picard.boundaryValue, ...
        'projectPerpendicular',true, ...
        'normalizedFluxEdges',(0:0.1:1).'));

shape = struct();
shape.R0 = geom.params.R0;
shape.a = geom.params.a;
shape.aspectRatio = shape.R0/shape.a;
shape.kappa = geom.params.kappa;
shape.delta = geom.params.delta;
shape.outboardMidplaneR = geom.outboardMidplaneR;
shape.inboardMidplaneR = geom.inboardMidplaneR;
shape.topR = geom.endPointR;
shape.topZ = geom.endPointZ;
shape.boundingBoxElongation = geom.boundingBoxElongation;

%% Collect result in the same interface used by main_cos
equilibrium = struct();
equilibrium.configuration = cfg;
equilibrium.geometry = geom;
equilibrium.mesh = mesh;
equilibrium.psi = psi;
equilibrium.profiles = cfg.profiles;
equilibrium.solver = solverResult;
equilibrium.continuation = continuation;
equilibrium.axis = axisData;
equilibrium.topology = topology;
equilibrium.field = field;
equilibrium.curvature = curvature;
equilibrium.millerShape = shape;

%% Text summary
nSteps = numel(continuation.steps);
lambda = zeros(nSteps,1);
nNodes = zeros(nSteps,1);
nElements = zeros(nSteps,1);
nPicard = zeros(nSteps,1);
finalResidual = zeros(nSteps,1);
psiAxis = zeros(nSteps,1);
for k = 1:nSteps
    lambda(k) = continuation.steps(k).lambda;
    nNodes(k) = continuation.steps(k).mesh.nNodes;
    nElements(k) = continuation.steps(k).mesh.nElements;
    nPicard(k) = continuation.steps(k).solver.nIterations;
    finalResidual(k) = continuation.steps(k).solver.finalResidual;
    psiAxis(k) = continuation.steps(k).solver.axisValue;
end
continuationTable = table(lambda,nNodes,nElements,nPicard, ...
    finalResidual,psiAxis);

fprintf('\nMiller D-shape Grad-Shafranov solve complete.\n')
disp(continuationTable)
fprintf('Final magnetic axis : R = %.8f, Z = %.8f, psi = %.8g\n', ...
    axisData.R,axisData.Z,axisData.psi)
fprintf('Final Picard solve  : %d iterations, residual = %.3e\n', ...
    solverResult.nIterations,solverResult.finalResidual)
fprintf('Flux topology       : passed = %d, O-points = %d, X-points = %d\n', ...
    topology.passed,topology.nOPoints,topology.nXPoints)
fprintf('Final mesh          : %d nodes, %d P1 elements\n', ...
    mesh.nNodes,mesh.nElements)
fprintf(['Miller parameters   : R0 = %.6f m, a = %.6f m, ' ...
         'R0/a = %.6f, kappa = %.6f, delta = %.6f\n'], ...
    shape.R0,shape.a,shape.aspectRatio,shape.kappa,shape.delta)
fprintf(['Boundary locations  : R_out = %.6f, R_in = %.6f, ' ...
         '(R_top,Z_top) = (%.6f,%.6f)\n'], ...
    shape.outboardMidplaneR,shape.inboardMidplaneR, ...
    shape.topR,shape.topZ)
fprintf('Bounding elongation : %.6f\n\n',shape.boundingBoxElongation)

%% Plots
if cfg.makePlots
    plot_flux(mesh,psi,struct( ...
        'axisData',axisData, ...
        'normalizedLevels',cfg.topologyLevels, ...
        'boundaryValue',cfg.picard.boundaryValue, ...
        'title','Miller D-shape equilibrium'));

    figure('Name','Miller boundary continuation','Color','w')
    colors = parula(nSteps);
    hold on
    for k = 1:nSteps
        boundary = continuation.steps(k).geom.closedPoints;
        plot(boundary(:,1),boundary(:,2),'-', ...
            'Color',colors(k,:),'LineWidth',1.2, ...
            'DisplayName',sprintf('lambda = %.2f',lambda(k)))
    end
    hold off
    axis equal tight
    grid on
    xlabel('R')
    ylabel('Z')
    title('Continuation into the Miller D-shape')
    legend('Location','bestoutside')

    figure('Name','Miller Picard convergence','Color','w')
    semilogy(1:solverResult.nIterations,solverResult.updateHistory, ...
        '-','LineWidth',1.5)
    hold on
    semilogy(1:solverResult.nIterations,solverResult.residualHistory, ...
        '--','LineWidth',1.5)
    hold off
    grid on
    xlabel('Picard iteration')
    ylabel('Relative measure')
    legend('iterate update','equation residual','Location','best')

    plot_curvature(mesh,curvature,struct( ...
        'titlePrefix',['Miller D-shape: ' ...
                       '\kappa\cdot\nabla p ' ...
                       '(dashed: zero boundary)']));
end


function F = reconstruct_F_miller( ...
        psi,psiAxis,psiBoundary,FBoundary,FFaxisValue,exponent)
span = psiBoundary-psiAxis;
psiNormalized = (psi-psiAxis)/span;
psiNormalized = min(max(psiNormalized,0),1);
F2 = FBoundary^2 ...
   -2*FFaxisValue*span/(exponent+1) ...
    .*(1-psiNormalized).^(exponent+1);
if any(F2(:)<=0)
    error('GS:mainMiller:NonPositiveFSquared', ...
        'The selected FBoundary and FFprime produce F^2<=0.');
end
F = sqrt(F2);
end
