%% GEQDSK PT0.6 reconstruction and local s-alpha diagram
% Produces the fixed-boundary GS equilibrium, rebuilds a centered radial
% surface stencil around psi_N=0.75, scans theta0, and plots the marginal
% stability diagram. Positive lambda_max is unstable.

main_PT06
pt06SAlpha = verify_local_salpha_scan(equilibrium,true);

targetIndex = pt06SAlpha.model.targetIndex;
targetProfiles = pt06SAlpha.localEquilibrium.profiles;
fprintf(['\nPT0.6 s-alpha target at psiN=%.3f: ' ...
         'q=%.6f, sHat=%.6f, alpha=%.6f\n'], ...
    pt06SAlpha.model.targetPsiN, ...
    targetProfiles.q(targetIndex), ...
    targetProfiles.sHat(targetIndex), ...
    targetProfiles.alpha(targetIndex))
fprintf('Critical alpha at reference shear = %.6f\n', ...
    pt06SAlpha.criticalAlphaAtReferenceShear)
