function root = setup_solve_GS()
    root = fileparts(mfilename('fullpath'));

    addpath(root, ...
        fullfile(root, 'GS', 'mesh'), ...
        fullfile(root, 'GS', 'fem'), ...
        fullfile(root, 'GS', 'solvers'), ...
        fullfile(root, 'GS', 'profiles'), ...
        fullfile(root, 'GS', 'post'), ...
        fullfile(root, 'GS', 'models'));
end